// Shared page manifest — the one list of every page on the site, used
// by smoke.spec.js (per-page load checks + the sitemap-drift test that
// keeps this list honest) and responsive.spec.js (phone-width overflow
// sweep). Lives outside any *.spec.js so requiring it never
// re-registers another spec's tests.
//
// In production the Worker serves clean URLs (/, /tools/,
// /tools/signal-scaling, /education/pid-basics, /contact) via
// html_handling. The local `python -m http.server` only knows real
// file paths, so the entries below hit the .html files directly — a
// directory like /tools/ still resolves to its index.html, so that one
// stays clean.
const PAGES = [
    { name: 'home',                   url: '/' },
    { name: 'tools landing',          url: '/tools/' },
    { name: 'signal scaling',         url: '/tools/signal-scaling.html' },
    { name: 'modbus register viewer', url: '/tools/modbus-register-viewer.html' },
    { name: 'bacnet/ip converter',    url: '/tools/bacnet-ip-converter.html' },
    { name: 'bacnet object reference', url: '/tools/bacnet-objects.html' },
    { name: 'bacnet vendor ids',      url: '/tools/bacnet-vendor-ids.html' },
    { name: 'bacnet units decoder',   url: '/tools/bacnet-units.html' },
    { name: 'bacnet error decoder',   url: '/tools/bacnet-error-codes.html' },
    { name: 'bacnet priority array',  url: '/tools/bacnet-priority.html' },
    { name: 'psychrometric chart',    url: '/tools/psychrometric-chart.html' },
    { name: 'economizer ratio',       url: '/tools/economizer-ratio.html' },
    { name: 'air mixing',             url: '/tools/air-mixing.html' },
    { name: 'coil sizing',            url: '/tools/coil-sizing.html' },
    { name: 'coil freeze risk',       url: '/tools/coil-freeze-risk.html' },
    { name: 'power & energy converter', url: '/tools/power-energy-converter.html' },
    { name: 'dew point calculator',   url: '/tools/dew-point-calculator.html' },
    { name: 'thermistor calculator',  url: '/tools/thermistor-calculator.html' },
    { name: 'refrigerant p-t',        url: '/tools/refrigerant-pt.html' },
    { name: 'valve cv sizing',        url: '/tools/valve-cv.html' },
    { name: 'valve authority',        url: '/tools/valve-authority.html' },
    { name: 'affinity laws',          url: '/tools/affinity-laws.html' },
    { name: 'waterside load',         url: '/tools/waterside-load.html' },
    { name: 'airflow',                url: '/tools/airflow.html' },
    { name: 'airside load',           url: '/tools/airside-load.html' },
    { name: 'duct traverse',          url: '/tools/duct-traverse.html' },
    { name: 'equipment airflow',      url: '/tools/equipment-airflow.html' },
    { name: 'minimum outdoor air',    url: '/tools/minimum-outdoor-air.html' },
    { name: 'duct sizer',             url: '/tools/duct-sizer.html' },
    { name: 'transformer va budget',  url: '/tools/transformer-sizing.html' },
    { name: 'wire run voltage drop',  url: '/tools/voltage-drop.html' },
    { name: 'field electrical quick calc', url: '/tools/electrical-quick-calc.html' },
    { name: 'bacnet mstp lesson',     url: '/education/bacnet-mstp.html' },
    { name: 'modbus function codes',  url: '/tools/modbus-functions.html' },
    { name: 'simulators landing',     url: '/simulators/' },
    { name: 'pid tuner',              url: '/simulators/pid-tuner.html' },
    { name: 'vfd mock',               url: '/simulators/vfd-mock.html' },
    { name: 'function-block editor',  url: '/simulators/function-block-editor.html' },
    { name: 'staging sequencer',      url: '/simulators/staging-sequencer.html' },
    { name: 'controller wiring',      url: '/simulators/controller-wiring.html' },
    { name: 'hydronic loop builder',  url: '/simulators/hydronic-loop-builder.html' },
    { name: 'refrigerant loop simulator', url: '/simulators/refrigerant-loop.html' },
    { name: 'bacnet hub',             url: '/bacnet/' },
    { name: 'forced-air hub',         url: '/forced-air/' },
    { name: 'hydronics hub',          url: '/hydronics/' },
    { name: 'refrigeration hub',      url: '/refrigeration/' },
    { name: 'guides landing',         url: '/guides/' },
    { name: 'education hub',          url: '/education/' },
    { name: 'education — pid basics',  url: '/education/pid-basics.html' },
    { name: 'education — controller wiring', url: '/education/controller-wiring.html' },
    { name: 'education — analog sensing', url: '/education/analog-sensing.html' },
    { name: 'education — temperature sensors', url: '/education/temperature-sensors.html' },
    { name: 'education — status and proof', url: '/education/status-and-proof.html' },
    { name: 'education — commanding actuators', url: '/education/commanding-actuators.html' },
    { name: 'education — start/stop commands', url: '/education/start-stop-commands.html' },
    { name: 'education — controls commissioning', url: '/education/controls-commissioning.html' },
    { name: 'education — hydronic loops', url: '/education/hydronic-loops.html' },
    { name: 'education — load piping', url: '/education/load-piping.html' },
    { name: 'education — vfds',       url: '/education/vfds.html' },
    { name: 'education — pump control', url: '/education/pump-control.html' },
    { name: 'education — equipment staging', url: '/education/equipment-staging.html' },
    { name: 'education — balancing',   url: '/education/balancing.html' },
    { name: 'education — coil selection', url: '/education/coil-selection.html' },
    { name: 'education — refrigerant cycle basics', url: '/education/refrigerant-cycle-basics.html' },
    { name: 'education — superheat & subcooling', url: '/education/superheat-subcooling.html' },
    { name: 'education — txv vs eev', url: '/education/metering-devices-txv-eev.html' },
    { name: 'education — psychrometrics basics', url: '/education/psychrometrics-basics.html' },
    { name: 'education — air handlers', url: '/education/air-handlers.html' },
    { name: 'education — economizers', url: '/education/economizers.html' },
    { name: 'education — building pressure', url: '/education/building-pressure.html' },
    { name: 'education — unit identification', url: '/education/air-unit-identification.html' },
    { name: 'education — vav systems', url: '/education/vav-systems.html' },
    { name: 'education — duct static control', url: '/education/duct-static-control.html' },
    { name: 'education — air balancing',  url: '/education/air-balancing.html' },
    { name: 'education — dedicated outdoor air', url: '/education/dedicated-outdoor-air.html' },
    { name: 'education — function blocks', url: '/education/function-blocks.html' },
    { name: 'education — boolean logic & latches', url: '/education/boolean-logic-latches.html' },
    { name: 'education — comparators & deadband', url: '/education/comparators-and-deadband.html' },
    { name: 'education — timers and delays', url: '/education/timers-and-delays.html' },
    { name: 'education — setpoint math & reset', url: '/education/setpoint-math-reset.html' },
    { name: 'education — reading a wiresheet', url: '/education/reading-a-wiresheet.html' },
    { name: 'education — modbus basics', url: '/education/modbus-basics.html' },
    { name: 'education — modbus decoding', url: '/education/modbus-decoding.html' },
    { name: 'education — bacnet vs modbus', url: '/education/bacnet-vs-modbus.html' },
    { name: 'education — bacnet basics', url: '/education/bacnet-basics.html' },
    { name: 'education — bacnet services', url: '/education/bacnet-services.html' },
    { name: 'education — bacnet networking', url: '/education/bacnet-networking.html' },
    { name: 'practice landing',       url: '/practice/' },
    { name: 'practice — modbus basics', url: '/practice/modbus-basics.html' },
    { name: 'practice — modbus decoding', url: '/practice/modbus-decoding.html' },
    { name: 'practice — bacnet basics', url: '/practice/bacnet-basics.html' },
    { name: 'practice — bacnet networking', url: '/practice/bacnet-networking.html' },
    { name: 'practice — bacnet mstp', url: '/practice/bacnet-mstp.html' },
    { name: 'practice — pump control', url: '/practice/pump-control.html' },
    { name: 'practice — hydronic loops', url: '/practice/hydronic-loops.html' },
    { name: 'practice — load piping', url: '/practice/load-piping.html' },
    { name: 'practice — balancing', url: '/practice/balancing.html' },
    { name: 'practice — refrigerant cycle basics', url: '/practice/refrigerant-cycle-basics.html' },
    { name: 'practice — superheat & subcooling', url: '/practice/superheat-subcooling.html' },
    { name: 'practice — metering devices txv/eev', url: '/practice/metering-devices-txv-eev.html' },
    { name: 'practice — pid basics', url: '/practice/pid-basics.html' },
    { name: 'practice — controller wiring', url: '/practice/controller-wiring.html' },
    { name: 'practice — analog sensing', url: '/practice/analog-sensing.html' },
    { name: 'practice — temperature sensors', url: '/practice/temperature-sensors.html' },
    { name: 'practice — status and proof', url: '/practice/status-and-proof.html' },
    { name: 'practice — commanding actuators', url: '/practice/commanding-actuators.html' },
    { name: 'practice — start/stop commands', url: '/practice/start-stop-commands.html' },
    { name: 'practice — vfds', url: '/practice/vfds.html' },
    { name: 'practice — function blocks', url: '/practice/function-blocks.html' },
    { name: 'practice — boolean logic & latches', url: '/practice/boolean-logic-latches.html' },
    { name: 'practice — comparators & deadband', url: '/practice/comparators-and-deadband.html' },
    { name: 'practice — timers and delays', url: '/practice/timers-and-delays.html' },
    { name: 'practice — setpoint math & reset', url: '/practice/setpoint-math-reset.html' },
    { name: 'practice — reading a wiresheet', url: '/practice/reading-a-wiresheet.html' },
    { name: 'practice — psychrometrics basics', url: '/practice/psychrometrics-basics.html' },
    { name: 'practice — air handlers', url: '/practice/air-handlers.html' },
    { name: 'practice — economizers', url: '/practice/economizers.html' },
    { name: 'practice — building pressure', url: '/practice/building-pressure.html' },
    { name: 'practice — unit identification', url: '/practice/air-unit-identification.html' },
    { name: 'practice — vav systems', url: '/practice/vav-systems.html' },
    { name: 'practice — duct static control', url: '/practice/duct-static-control.html' },
    { name: 'practice — equipment staging', url: '/practice/equipment-staging.html' },
    { name: 'practice — surviving first months', url: '/practice/surviving-first-months.html' },
    { name: 'practice — controller swap', url: '/practice/controller-swap.html' },
    { name: 'practice — field wiring & sensors', url: '/practice/field-wiring-sensors.html' },
    { name: 'practice — sequencing scenarios', url: '/practice/sequencing-scenarios.html' },
    { name: 'practice — troubleshooting', url: '/practice/troubleshooting.html' },
    { name: 'practice — wiresheet traces', url: '/practice/wiresheet-traces.html' },
    { name: 'contact',                url: '/contact.html' },
    { name: 'privacy',                url: '/privacy.html' },
];

module.exports = PAGES;
