// BACnet error / reject / abort enumerations — GENERATED FILE, do not hand-edit.
//
// Source: https://raw.githubusercontent.com/bacnet-stack/bacnet-stack/master/src/bacnet/bacenum.h
//   (bacnet-stack's error enums — the de-facto machine-readable form of the
//    ASHRAE 135 error-class / error-code / reject / abort enumerations,
//    which are paywalled)
// Retrieved: 2026-07-12 · 8 classes · 225 codes · 11 reject · 12 abort
// Regenerate: npm run import-bacnet-errors
//   (.github/scripts/import-bacnet-errors.mjs — validates before writing)
//
// Enum TRUTH only (id → name). Field-accurate plain-English descriptions
// live in the hand-authored html/_data/bacnetErrorNotes.js and are overlaid
// by /tools/bacnet-error-codes.html at build time. Names are the
// bacnet-stack spellings; the field-common rows should read cleanly, the
// long tail (BACnet/SC transport, HTTP/TLS/DNS, OAuth-scope codes) is
// edition-2020+ and rarely seen — verify exact wording against ASHRAE 135.
//
// Name strings render with `| safe` (site-authored, never user input).

const errorClass = [
    { id: 0, name: "device" },
    { id: 1, name: "object" },
    { id: 2, name: "property" },
    { id: 3, name: "resources" },
    { id: 4, name: "security" },
    { id: 5, name: "services" },
    { id: 6, name: "vt" },
    { id: 7, name: "communication" },
];

const errorCode = [
    { id: 0, name: "other" },
    { id: 1, name: "authentication-failed" },
    { id: 2, name: "configuration-in-progress" },
    { id: 3, name: "device-busy" },
    { id: 4, name: "dynamic-creation-not-supported" },
    { id: 5, name: "file-access-denied" },
    { id: 6, name: "incompatible-security-levels" },
    { id: 7, name: "inconsistent-parameters" },
    { id: 8, name: "inconsistent-selection-criterion" },
    { id: 9, name: "invalid-data-type" },
    { id: 10, name: "invalid-file-access-method" },
    { id: 11, name: "invalid-file-start-position" },
    { id: 12, name: "invalid-operator-name" },
    { id: 13, name: "invalid-parameter-data-type" },
    { id: 14, name: "invalid-time-stamp" },
    { id: 15, name: "key-generation-error" },
    { id: 16, name: "missing-required-parameter" },
    { id: 17, name: "no-objects-of-specified-type" },
    { id: 18, name: "no-space-for-object" },
    { id: 19, name: "no-space-to-add-list-element" },
    { id: 20, name: "no-space-to-write-property" },
    { id: 21, name: "no-vt-sessions-available" },
    { id: 22, name: "property-is-not-a-list" },
    { id: 23, name: "object-deletion-not-permitted" },
    { id: 24, name: "object-identifier-already-exists" },
    { id: 25, name: "operational-problem" },
    { id: 26, name: "password-failure" },
    { id: 27, name: "read-access-denied" },
    { id: 28, name: "security-not-supported" },
    { id: 29, name: "service-request-denied" },
    { id: 30, name: "timeout" },
    { id: 31, name: "unknown-object" },
    { id: 32, name: "unknown-property" },
    { id: 34, name: "unknown-vt-class" },
    { id: 35, name: "unknown-vt-session" },
    { id: 36, name: "unsupported-object-type" },
    { id: 37, name: "value-out-of-range" },
    { id: 38, name: "vt-session-already-closed" },
    { id: 39, name: "vt-session-termination-failure" },
    { id: 40, name: "write-access-denied" },
    { id: 41, name: "character-set-not-supported" },
    { id: 42, name: "invalid-array-index" },
    { id: 43, name: "cov-subscription-failed" },
    { id: 44, name: "not-cov-property" },
    { id: 45, name: "optional-functionality-not-supported" },
    { id: 46, name: "invalid-configuration-data" },
    { id: 47, name: "datatype-not-supported" },
    { id: 48, name: "duplicate-name" },
    { id: 49, name: "duplicate-object-id" },
    { id: 50, name: "property-is-not-an-array" },
    { id: 51, name: "abort-buffer-overflow" },
    { id: 52, name: "abort-invalid-apdu-in-this-state" },
    { id: 53, name: "abort-preempted-by-higher-priority-task" },
    { id: 54, name: "abort-segmentation-not-supported" },
    { id: 56, name: "abort-other" },
    { id: 57, name: "invalid-tag" },
    { id: 58, name: "network-down" },
    { id: 59, name: "reject-buffer-overflow" },
    { id: 60, name: "reject-inconsistent-parameters" },
    { id: 61, name: "reject-invalid-parameter-data-type" },
    { id: 62, name: "reject-invalid-tag" },
    { id: 63, name: "reject-missing-required-parameter" },
    { id: 64, name: "reject-parameter-out-of-range" },
    { id: 65, name: "reject-too-many-arguments" },
    { id: 66, name: "reject-undefined-enumeration" },
    { id: 67, name: "reject-unrecognized-service" },
    { id: 69, name: "reject-other" },
    { id: 70, name: "unknown-device" },
    { id: 71, name: "unknown-route" },
    { id: 72, name: "value-not-initialized" },
    { id: 73, name: "invalid-event-state" },
    { id: 74, name: "no-alarm-configured" },
    { id: 75, name: "log-buffer-full" },
    { id: 76, name: "logged-value-purged" },
    { id: 77, name: "no-property-specified" },
    { id: 78, name: "not-configured-for-triggered-logging" },
    { id: 79, name: "unknown-subscription" },
    { id: 80, name: "parameter-out-of-range" },
    { id: 81, name: "list-element-not-found" },
    { id: 82, name: "busy" },
    { id: 83, name: "communication-disabled" },
    { id: 84, name: "success" },
    { id: 85, name: "access-denied" },
    { id: 86, name: "bad-destination-address" },
    { id: 87, name: "bad-destination-device-id" },
    { id: 88, name: "bad-signature" },
    { id: 89, name: "bad-source-address" },
    { id: 90, name: "bad-timestamp" },
    { id: 91, name: "cannot-use-key" },
    { id: 92, name: "cannot-verify-message-id" },
    { id: 93, name: "correct-key-revision" },
    { id: 94, name: "destination-device-id-required" },
    { id: 95, name: "duplicate-message" },
    { id: 96, name: "encryption-not-configured" },
    { id: 97, name: "encryption-required" },
    { id: 98, name: "incorrect-key" },
    { id: 99, name: "invalid-key-data" },
    { id: 100, name: "key-update-in-progress" },
    { id: 101, name: "malformed-message" },
    { id: 102, name: "not-key-server" },
    { id: 103, name: "security-not-configured" },
    { id: 104, name: "source-security-required" },
    { id: 105, name: "too-many-keys" },
    { id: 106, name: "unknown-authentication-type" },
    { id: 107, name: "unknown-key" },
    { id: 108, name: "unknown-key-revision" },
    { id: 109, name: "unknown-source-message" },
    { id: 110, name: "not-router-to-dnet" },
    { id: 111, name: "router-busy" },
    { id: 112, name: "unknown-network-message" },
    { id: 113, name: "message-too-long" },
    { id: 114, name: "security-error" },
    { id: 115, name: "addressing-error" },
    { id: 116, name: "write-bdt-failed" },
    { id: 117, name: "read-bdt-failed" },
    { id: 118, name: "register-foreign-device-failed" },
    { id: 119, name: "read-fdt-failed" },
    { id: 120, name: "delete-fdt-entry-failed" },
    { id: 121, name: "distribute-broadcast-failed" },
    { id: 122, name: "unknown-file-size" },
    { id: 123, name: "abort-apdu-too-long" },
    { id: 124, name: "abort-application-exceeded-reply-time" },
    { id: 125, name: "abort-out-of-resources" },
    { id: 126, name: "abort-tsm-timeout" },
    { id: 127, name: "abort-window-size-out-of-range" },
    { id: 128, name: "file-full" },
    { id: 129, name: "inconsistent-configuration" },
    { id: 130, name: "inconsistent-object-type" },
    { id: 131, name: "internal-error" },
    { id: 132, name: "not-configured" },
    { id: 133, name: "out-of-memory" },
    { id: 134, name: "value-too-long" },
    { id: 135, name: "abort-insufficient-security" },
    { id: 136, name: "abort-security-error" },
    { id: 137, name: "duplicate-entry" },
    { id: 138, name: "invalid-value-in-this-state" },
    { id: 139, name: "invalid-operation-in-this-state" },
    { id: 140, name: "list-item-not-numbered" },
    { id: 141, name: "list-item-not-timestamped" },
    { id: 142, name: "invalid-data-encoding" },
    { id: 143, name: "bvlc-function-unknown" },
    { id: 145, name: "header-encoding-error" },
    { id: 146, name: "header-not-understood" },
    { id: 147, name: "message-incomplete" },
    { id: 148, name: "not-a-bacnet-sc-hub" },
    { id: 149, name: "payload-expected" },
    { id: 150, name: "unexpected-data" },
    { id: 151, name: "node-duplicate-vmac" },
    { id: 152, name: "http-unexpected-response-code" },
    { id: 153, name: "http-no-upgrade" },
    { id: 154, name: "http-resource-not-local" },
    { id: 155, name: "http-proxy-authentication-failed" },
    { id: 156, name: "http-response-timeout" },
    { id: 157, name: "http-response-syntax-error" },
    { id: 158, name: "http-response-value-error" },
    { id: 159, name: "http-response-missing-header" },
    { id: 160, name: "http-websocket-header-error" },
    { id: 161, name: "http-upgrade-required" },
    { id: 162, name: "http-upgrade-error" },
    { id: 163, name: "http-temporary-unavailable" },
    { id: 164, name: "http-not-a-server" },
    { id: 165, name: "http-error" },
    { id: 166, name: "websocket-scheme-not-supported" },
    { id: 167, name: "websocket-unknown-control-message" },
    { id: 168, name: "websocket-close-error" },
    { id: 169, name: "websocket-closed-by-peer" },
    { id: 170, name: "websocket-endpoint-leaves" },
    { id: 171, name: "websocket-protocol-error" },
    { id: 172, name: "websocket-data-not-accepted" },
    { id: 173, name: "websocket-closed-abnormally" },
    { id: 174, name: "websocket-data-inconsistent" },
    { id: 175, name: "websocket-data-against-policy" },
    { id: 176, name: "websocket-frame-too-long" },
    { id: 177, name: "websocket-extension-missing" },
    { id: 178, name: "websocket-request-unavailable" },
    { id: 179, name: "websocket-error" },
    { id: 180, name: "tls-client-certificate-error" },
    { id: 181, name: "tls-server-certificate-error" },
    { id: 182, name: "tls-client-authentication-failed" },
    { id: 183, name: "tls-server-authentication-failed" },
    { id: 184, name: "tls-client-certificate-expired" },
    { id: 185, name: "tls-server-certificate-expired" },
    { id: 186, name: "tls-client-certificate-revoked" },
    { id: 187, name: "tls-server-certificate-revoked" },
    { id: 188, name: "tls-error" },
    { id: 189, name: "dns-unavailable" },
    { id: 190, name: "dns-name-resolution-failed" },
    { id: 191, name: "dns-resolver-failure" },
    { id: 192, name: "dns-error" },
    { id: 193, name: "tcp-connect-timeout" },
    { id: 194, name: "tcp-connection-refused" },
    { id: 195, name: "tcp-closed-by-local" },
    { id: 196, name: "tcp-closed-other" },
    { id: 197, name: "tcp-error" },
    { id: 198, name: "ip-address-not-reachable" },
    { id: 199, name: "ip-error" },
    { id: 200, name: "certificate-expired" },
    { id: 201, name: "certificate-invalid" },
    { id: 202, name: "certificate-malformed" },
    { id: 203, name: "certificate-revoked" },
    { id: 204, name: "unknown-security-key" },
    { id: 205, name: "referenced-port-in-error" },
    { id: 206, name: "not-enabled" },
    { id: 207, name: "adjust-scope-required" },
    { id: 208, name: "auth-scope-required" },
    { id: 209, name: "bind-scope-required" },
    { id: 210, name: "config-scope-required" },
    { id: 211, name: "control-scope-required" },
    { id: 212, name: "extended-scope-required" },
    { id: 213, name: "incorrect-client" },
    { id: 214, name: "install-scope-required" },
    { id: 215, name: "insufficient-scope" },
    { id: 217, name: "no-policy" },
    { id: 218, name: "revoked-token" },
    { id: 219, name: "override-scope-required" },
    { id: 220, name: "inactive-token" },
    { id: 221, name: "unknown-audience" },
    { id: 222, name: "unknown-client" },
    { id: 223, name: "unknown-scope" },
    { id: 224, name: "view-scope-required" },
    { id: 225, name: "incorrect-audience" },
    { id: 226, name: "incorrect-client-origin" },
    { id: 227, name: "invalid-array-size" },
    { id: 228, name: "incorrect-issuer" },
    { id: 229, name: "invalid-token" },
];

const rejectReason = [
    { id: 0, name: "other" },
    { id: 1, name: "buffer-overflow" },
    { id: 2, name: "inconsistent-parameters" },
    { id: 3, name: "invalid-parameter-data-type" },
    { id: 4, name: "invalid-tag" },
    { id: 5, name: "missing-required-parameter" },
    { id: 6, name: "parameter-out-of-range" },
    { id: 7, name: "too-many-arguments" },
    { id: 8, name: "undefined-enumeration" },
    { id: 9, name: "unrecognized-service" },
    { id: 10, name: "invalid-data-encoding" },
];

const abortReason = [
    { id: 0, name: "other" },
    { id: 1, name: "buffer-overflow" },
    { id: 2, name: "invalid-apdu-in-this-state" },
    { id: 3, name: "preempted-by-higher-priority-task" },
    { id: 4, name: "segmentation-not-supported" },
    { id: 5, name: "security-error" },
    { id: 6, name: "insufficient-security" },
    { id: 7, name: "window-size-out-of-range" },
    { id: 8, name: "application-exceeded-reply-time" },
    { id: 9, name: "out-of-resources" },
    { id: 10, name: "tsm-timeout" },
    { id: 11, name: "apdu-too-long" },
];

module.exports = {
    errorClass,
    errorCode,
    rejectReason,
    abortReason,
    counts: {
        classes: 8,
        codes: 225,
        reject: 11,
        abort: 12,
    },
    retrieved: '2026-07-12',
    source: 'https://raw.githubusercontent.com/bacnet-stack/bacnet-stack/master/src/bacnet/bacenum.h',
};
