// BACnet vendor IDs — GENERATED FILE, do not hand-edit.
//
// Source: https://bacnet.org/assigned-vendor-ids/ (the official ASHRAE registry)
// Retrieved: 2026-07-08 · 1629 entries · highest ID 1631
// Regenerate: npm run import-vendor-ids
//   (.github/scripts/import-bacnet-vendor-ids.mjs — validates before writing)
//
// Republishes ONLY id + organization. The registry also lists a contact
// person and mailing address per vendor — deliberately dropped at import.
// IDs are assigned once and never reassigned; numbers missing from the
// sequence are withdrawn registrations, and IDs above 1631 postdate
// this snapshot.
//
// Org strings are entity-DECODED plain text; the lookup page renders them
// with Nunjucks autoescaping (no `| safe`) — the opposite of the
// site-authored bacnetEnums.js, whose strings render `| safe`.

const vendors = [
    { id: 0, org: "ASHRAE" },
    { id: 1, org: "NIST" },
    { id: 2, org: "The Trane Company" },
    { id: 3, org: "Daikin Applied Americas" },
    { id: 4, org: "PolarSoft" },
    { id: 5, org: "Johnson Controls, Inc." },
    { id: 6, org: "ABB (Formerly American Auto-Matrix)" },
    { id: 7, org: "Siemens Schweiz AG" },
    { id: 8, org: "Delta Controls" },
    { id: 9, org: "Siemens Schweiz AG" },
    { id: 10, org: "Schneider Electric" },
    { id: 11, org: "TAC" },
    { id: 12, org: "Orion Analysis Corporation" },
    { id: 13, org: "Teletrol Systems Inc." },
    { id: 14, org: "Cimetrics Technology" },
    { id: 15, org: "Cornell University" },
    { id: 16, org: "United Technologies Carrier" },
    { id: 17, org: "Honeywell Inc." },
    { id: 18, org: "Alerton / Honeywell" },
    { id: 19, org: "TAC AB" },
    { id: 20, org: "Hewlett-Packard Company" },
    { id: 21, org: "Dorsette’s Inc." },
    { id: 22, org: "Siemens Schweiz AG" },
    { id: 23, org: "York Controls Group" },
    { id: 24, org: "Automated Logic Corporation" },
    { id: 25, org: "CSI Control Systems International" },
    { id: 26, org: "Phoenix Controls Corporation" },
    { id: 27, org: "Innovex Technologies, Inc." },
    { id: 28, org: "KMC Controls, Inc." },
    { id: 29, org: "Xn Technologies, Inc." },
    { id: 30, org: "Hyundai Information Technology Co., Ltd." },
    { id: 31, org: "Tokimec Inc." },
    { id: 32, org: "Simplex" },
    { id: 33, org: "North Building Technologies Limited" },
    { id: 34, org: "Notifier" },
    { id: 35, org: "Reliable Controls Corporation" },
    { id: 36, org: "Tridium Inc." },
    { id: 37, org: "MSA Safety" },
    { id: 38, org: "Silicon Energy" },
    { id: 39, org: "Kieback & Peter GmbH & Co KG" },
    { id: 40, org: "Anacon Systems, Inc." },
    { id: 41, org: "Systems Controls & Instruments, LLC" },
    { id: 42, org: "Acuity Brands Lighting, Inc." },
    { id: 43, org: "Micropower Manufacturing" },
    { id: 44, org: "Matrix Controls" },
    { id: 45, org: "METALAIRE" },
    { id: 46, org: "ESS Engineering" },
    { id: 47, org: "Sphere Systems Pty Ltd." },
    { id: 48, org: "Walker Technologies Corporation" },
    { id: 49, org: "H I Solutions, Inc." },
    { id: 50, org: "MBS GmbH" },
    { id: 51, org: "SAMSON AG" },
    { id: 52, org: "Badger Meter Inc." },
    { id: 53, org: "DAIKIN Industries Ltd." },
    { id: 54, org: "NARA Controls Inc." },
    { id: 55, org: "Mammoth Inc." },
    { id: 56, org: "Liebert Corporation" },
    { id: 57, org: "SEMCO Incorporated" },
    { id: 58, org: "Air Monitor Corporation" },
    { id: 59, org: "TRIATEK, LLC" },
    { id: 60, org: "NexLight" },
    { id: 61, org: "Multistack" },
    { id: 62, org: "TSI Incorporated" },
    { id: 63, org: "Weather-Rite, Inc." },
    { id: 64, org: "Dunham-Bush" },
    { id: 65, org: "Reliance Electric" },
    { id: 66, org: "LCS Inc." },
    { id: 67, org: "Regulator Australia PTY Ltd." },
    { id: 68, org: "Touch-Plate Lighting Controls" },
    { id: 69, org: "Amann GmbH" },
    { id: 70, org: "Parameter LLC" },
    { id: 71, org: "Cardkey Systems" },
    { id: 72, org: "SECOM Co., Ltd." },
    { id: 73, org: "ABB Gebäudetechnik AG Bereich NetServ" },
    { id: 74, org: "KNX Association cvba" },
    { id: 75, org: "Institute of Electrical Installation Engineers of Japan (IEIEJ)" },
    { id: 76, org: "Nohmi Bosai, Ltd." },
    { id: 77, org: "Carel Industries S.p.A." },
    { id: 78, org: "UTC Fire & Security España, S.L." },
    { id: 79, org: "Hochiki Corporation" },
    { id: 80, org: "Fr. Sauter AG" },
    { id: 81, org: "Matsushita Electric Works, Ltd." },
    { id: 82, org: "Mitsubishi Electric Corporation, Inazawa Works" },
    { id: 83, org: "Mitsubishi Heavy Industries, Ltd." },
    { id: 84, org: "Xylem, Inc." },
    { id: 85, org: "Yamatake Building Systems Co., Ltd." },
    { id: 86, org: "The Watt Stopper, Inc." },
    { id: 87, org: "Aichi Tokei Denki Co., Ltd." },
    { id: 88, org: "Activation Technologies, LLC" },
    { id: 89, org: "Saia-Burgess Controls, Ltd." },
    { id: 90, org: "Hitachi, Ltd." },
    { id: 91, org: "Novar Corp./Trend Control Systems Ltd." },
    { id: 92, org: "Mitsubishi Electric Lighting Corporation" },
    { id: 93, org: "Argus Control Systems, Ltd." },
    { id: 94, org: "Kyuki Corporation" },
    { id: 95, org: "Richards-Zeta Building Intelligence, Inc." },
    { id: 96, org: "Scientech R&D, Inc." },
    { id: 97, org: "VCI Controls, Inc." },
    { id: 98, org: "Toshiba Corporation" },
    { id: 99, org: "Mitsubishi Electric Corporation Air Conditioning & Refrigeration Systems Works" },
    { id: 100, org: "Custom Mechanical Equipment, LLC" },
    { id: 101, org: "ClimateMaster" },
    { id: 102, org: "ICP Panel-Tec, Inc." },
    { id: 103, org: "D-Tek Controls" },
    { id: 104, org: "NEC Engineering, Ltd." },
    { id: 105, org: "PRIVA BV" },
    { id: 106, org: "Meidensha Corporation" },
    { id: 107, org: "JCI Systems Integration Services" },
    { id: 108, org: "Freedom Corporation" },
    { id: 109, org: "Neuberger Gebäudeautomation GmbH" },
    { id: 110, org: "eZi Controls" },
    { id: 111, org: "Leviton Manufacturing" },
    { id: 112, org: "Fujitsu Limited" },
    { id: 113, org: "Vertiv (Formerly Emerson Network Power)" },
    { id: 114, org: "S. A. Armstrong, Ltd." },
    { id: 115, org: "Visonet AG" },
    { id: 116, org: "M&M Systems, Inc." },
    { id: 117, org: "Custom Software Engineering" },
    { id: 118, org: "Nittan Company, Limited" },
    { id: 119, org: "Elutions Inc. (Wizcon Systems SAS)" },
    { id: 120, org: "Pacom Systems Pty., Ltd." },
    { id: 121, org: "Unico, Inc." },
    { id: 122, org: "Ebtron, Inc." },
    { id: 123, org: "Scada Engine" },
    { id: 124, org: "Lenze Americas (Formerly: AC Technology Corporation)" },
    { id: 125, org: "Eagle Technology" },
    { id: 126, org: "Data Aire, Inc." },
    { id: 127, org: "ABB, Inc." },
    { id: 128, org: "Transbit Sp. z o. o." },
    { id: 129, org: "Carrier Japan Corporation" },
    { id: 130, org: "Shenzhen Junzhi Hi-Tech Co., Ltd." },
    { id: 131, org: "Tokai Soft" },
    { id: 132, org: "Blue Ridge Technologies" },
    { id: 133, org: "Veris Industries" },
    { id: 134, org: "Centaurus Prime" },
    { id: 135, org: "Sand Network Systems" },
    { id: 136, org: "Regulvar, Inc." },
    { id: 137, org: "AFDtek Division of Fastek International Inc." },
    { id: 138, org: "PowerCold Comfort Air Solutions, Inc." },
    { id: 139, org: "I Controls" },
    { id: 140, org: "Viconics Electronics, Inc." },
    { id: 141, org: "Yaskawa America, Inc." },
    { id: 142, org: "DEOS control systems GmbH" },
    { id: 143, org: "Digitale Mess- und Steuersysteme AG" },
    { id: 144, org: "Fujitsu General Limited" },
    { id: 145, org: "Project Engineering S.r.l." },
    { id: 146, org: "Sanyo Electric Co., Ltd." },
    { id: 147, org: "Integrated Information Systems, Inc." },
    { id: 148, org: "Temco Controls, Ltd." },
    { id: 149, org: "Airtek International Inc." },
    { id: 150, org: "Advantech Corporation" },
    { id: 151, org: "Titan Products, Ltd." },
    { id: 152, org: "Regel Partners" },
    { id: 153, org: "National Environmental Product" },
    { id: 154, org: "Unitec Corporation" },
    { id: 155, org: "Kanden Engineering Company" },
    { id: 156, org: "Messner Gebäudetechnik GmbH" },
    { id: 157, org: "Integrated.CH" },
    { id: 158, org: "Price Industries" },
    { id: 159, org: "SE-Elektronic GmbH" },
    { id: 160, org: "Rockwell Automation" },
    { id: 161, org: "Enflex Corp." },
    { id: 162, org: "ASI Controls" },
    { id: 163, org: "SysMik GmbH Dresden" },
    { id: 164, org: "HSC Regelungstechnik GmbH" },
    { id: 165, org: "Smart Temp Australia Pty. Ltd." },
    { id: 166, org: "Cooper Controls" },
    { id: 167, org: "Duksan Mecasys Co., Ltd." },
    { id: 168, org: "Fuji IT Co., Ltd." },
    { id: 169, org: "Vacon Plc" },
    { id: 170, org: "Leader Controls" },
    { id: 171, org: "ABB (Formerly Cylon Controls, Ltd)" },
    { id: 172, org: "Compas" },
    { id: 173, org: "Mitsubishi Electric Building Techno-Service Co., Ltd." },
    { id: 174, org: "Building Control Integrators" },
    { id: 175, org: "ITG Worldwide (M) Sdn Bhd" },
    { id: 176, org: "Lutron Electronics Co., Inc." },
    { id: 177, org: "Cooper-Atkins Corporation" },
    { id: 178, org: "LOYTEC Electronics GmbH" },
    { id: 179, org: "ProLon" },
    { id: 180, org: "Mega Controls Limited" },
    { id: 181, org: "Micro Control Systems, Inc." },
    { id: 182, org: "Kiyon, Inc." },
    { id: 183, org: "Dust Networks" },
    { id: 184, org: "Advanced Building Automation Systems" },
    { id: 185, org: "Hermos AG" },
    { id: 186, org: "CEZIM" },
    { id: 187, org: "Softing" },
    { id: 188, org: "Lynxspring, Inc." },
    { id: 189, org: "Schneider Toshiba Inverter Europe" },
    { id: 190, org: "Danfoss Drives A/S" },
    { id: 191, org: "Eaton Corporation" },
    { id: 192, org: "Matyca S.A." },
    { id: 193, org: "Botech AB" },
    { id: 194, org: "Noveo, Inc." },
    { id: 195, org: "AMEV" },
    { id: 196, org: "Yokogawa Electric Corporation" },
    { id: 197, org: "Bosch Building Automation GmbH" },
    { id: 198, org: "Exact Logic" },
    { id: 199, org: "Mass Electronics Pty Ltd dba Innotech Control Systems Australia" },
    { id: 200, org: "Kandenko Co., Ltd." },
    { id: 201, org: "DTF, Daten-Technik Fries" },
    { id: 202, org: "Klimasoft, Ltd." },
    { id: 203, org: "Toshiba Schneider Inverter Corporation" },
    { id: 204, org: "Control Applications, Ltd." },
    { id: 205, org: "CIMON CO., Ltd." },
    { id: 206, org: "Onicon Incorporated" },
    { id: 207, org: "Automation Displays, Inc." },
    { id: 208, org: "Control Solutions, Inc." },
    { id: 209, org: "Remsdaq Limited" },
    { id: 210, org: "NTT Facilities, Inc." },
    { id: 211, org: "VIPA GmbH" },
    { id: 212, org: "TSC21 Association of Japan" },
    { id: 213, org: "Strato Automation" },
    { id: 214, org: "HRW Limited" },
    { id: 215, org: "Lighting Control & Design, Inc." },
    { id: 216, org: "Mercy Electronic and Electrical Industries" },
    { id: 217, org: "Samsung SDS Co., Ltd" },
    { id: 218, org: "Impact Facility Solutions, Inc." },
    { id: 219, org: "Aircuity" },
    { id: 220, org: "Control Techniques, Ltd." },
    { id: 221, org: "OpenGeneral Pty., Ltd." },
    { id: 222, org: "WAGO Kontakttechnik GmbH & Co. KG" },
    { id: 223, org: "Franklin Electric" },
    { id: 224, org: "Chloride Power Protection Company" },
    { id: 225, org: "Computrols, Inc." },
    { id: 226, org: "Phoenix Contact GmbH & Co. KG" },
    { id: 227, org: "Grundfos Management A/S" },
    { id: 228, org: "Ridder Drive Systems" },
    { id: 229, org: "Soft Device SDN BHD" },
    { id: 230, org: "Integrated Control Technology Limited" },
    { id: 231, org: "AIRxpert Systems, Inc." },
    { id: 232, org: "Microtrol Limited" },
    { id: 233, org: "Red Lion Controls" },
    { id: 234, org: "Digital Electronics Corporation" },
    { id: 235, org: "Ennovatis GmbH" },
    { id: 236, org: "Serotonin Software Technologies, Inc." },
    { id: 237, org: "LS Industrial Systems Co., Ltd." },
    { id: 238, org: "Square D Company" },
    { id: 239, org: "S Squared Innovations, Inc." },
    { id: 240, org: "Aricent Ltd." },
    { id: 241, org: "EtherMetrics, LLC" },
    { id: 242, org: "Industrial Control Communications, Inc." },
    { id: 243, org: "Paragon Controls, Inc." },
    { id: 244, org: "A. O. Smith Corporation" },
    { id: 245, org: "Contemporary Control Systems, Inc." },
    { id: 246, org: "HMS Industrial Networks SLU" },
    { id: 247, org: "Ingenieurgesellschaft N. Hartleb mbH" },
    { id: 248, org: "Heat-Timer Corporation" },
    { id: 249, org: "Ingrasys Technology, Inc." },
    { id: 250, org: "Costerm Building Automation" },
    { id: 251, org: "WILO SE" },
    { id: 252, org: "Embedia Technologies Corp." },
    { id: 253, org: "Technilog" },
    { id: 254, org: "HR Controls Ltd. & Co. KG" },
    { id: 255, org: "Lennox International, Inc." },
    { id: 256, org: "RK-Tec Rauchklappen-Steuerungssysteme GmbH & Co. KG" },
    { id: 257, org: "Thermomax, Ltd." },
    { id: 258, org: "ELCON Electronic Control, Ltd." },
    { id: 259, org: "Larmia Control AB" },
    { id: 260, org: "BACnet Stack at SourceForge" },
    { id: 261, org: "G4S Security Services A/S" },
    { id: 262, org: "Exor International S.p.A." },
    { id: 263, org: "Cristal Controles" },
    { id: 264, org: "Regin AB" },
    { id: 265, org: "Dimension Software, Inc." },
    { id: 266, org: "SynapSense Corporation" },
    { id: 267, org: "Beijing Nantree Electronic Co., Ltd." },
    { id: 268, org: "Camus Hydronics Ltd." },
    { id: 269, org: "Kawasaki Heavy Industries, Ltd." },
    { id: 270, org: "Critical Environment Technologies" },
    { id: 271, org: "ILSHIN IBS Co., Ltd." },
    { id: 272, org: "ELESTA Energy Control AG" },
    { id: 273, org: "KROPMAN Installatietechniek" },
    { id: 274, org: "Baldor Electric Company" },
    { id: 275, org: "INGA mbH" },
    { id: 276, org: "GE Consumer & Industrial" },
    { id: 277, org: "Functional Devices, Inc." },
    { id: 278, org: "StudioSC" },
    { id: 279, org: "MG CO., LTD." },
    { id: 280, org: "Yokota Co., Ltd." },
    { id: 281, org: "Hitranse Technology Co., LTD" },
    { id: 282, org: "Vigilent Corporation" },
    { id: 283, org: "Kele, Inc." },
    { id: 284, org: "BELIMO Automation AG" },
    { id: 285, org: "Gentec" },
    { id: 286, org: "Embedded Science Labs, LLC" },
    { id: 287, org: "Parker Hannifin Corporation" },
    { id: 288, org: "MaCaPS International Limited" },
    { id: 289, org: "Link4 Corporation" },
    { id: 290, org: "Romutec Steuer-u. Regelsysteme GmbH" },
    { id: 291, org: "Pribusin, Inc." },
    { id: 292, org: "Advantage Controls" },
    { id: 293, org: "Critical Room Control" },
    { id: 294, org: "LEGRAND" },
    { id: 295, org: "Tongdy Control Technology Co., Ltd." },
    { id: 296, org: "ISSARO Integrierte Systemtechnik" },
    { id: 297, org: "Pro-Dev Industries" },
    { id: 298, org: "DRI-STEEM" },
    { id: 299, org: "Creative Electronic GmbH" },
    { id: 300, org: "Swegon AB" },
    { id: 301, org: "FIRVENA s.r.o." },
    { id: 302, org: "Hitachi Appliances, Inc." },
    { id: 303, org: "Real Time Automation, Inc." },
    { id: 304, org: "ITEC Hankyu-Hanshin Co." },
    { id: 305, org: "Cyrus E&M Engineering Co., Ltd." },
    { id: 306, org: "Badger Meter" },
    { id: 307, org: "Cirrascale Corporation" },
    { id: 308, org: "Elesta GmbH Building Automation" },
    { id: 309, org: "Securiton" },
    { id: 310, org: "OSlsoft, Inc." },
    { id: 311, org: "Hanazeder Electronic GmbH" },
    { id: 312, org: "Honeywell Security Deutschland, Novar GmbH" },
    { id: 313, org: "Siemens Industry, Inc." },
    { id: 314, org: "ETM Professional Control GmbH" },
    { id: 315, org: "Meitav-tec, Ltd." },
    { id: 316, org: "Janitza Electronics GmbH" },
    { id: 317, org: "MKS Nordhausen" },
    { id: 318, org: "De Gier Drive Systems B.V." },
    { id: 319, org: "Cypress Envirosystems" },
    { id: 320, org: "SMARTron s.r.o." },
    { id: 321, org: "Verari Systems, Inc." },
    { id: 322, org: "K-W Electronic Service, Inc." },
    { id: 323, org: "ALFA-SMART Energy Management" },
    { id: 324, org: "Telkonet, Inc." },
    { id: 325, org: "Securiton GmbH" },
    { id: 326, org: "Cemtrex, Inc." },
    { id: 327, org: "Performance Technologies, Inc." },
    { id: 328, org: "Xtralis (Aust) Pty Ltd" },
    { id: 329, org: "TROX SE" },
    { id: 330, org: "Beijing Hysine Technology Co., Ltd" },
    { id: 331, org: "RCK Controls, Inc." },
    { id: 332, org: "Distech Controls SAS" },
    { id: 333, org: "Novar/Honeywell" },
    { id: 334, org: "S4 Integration Solutions" },
    { id: 335, org: "Schneider Electric" },
    { id: 336, org: "LHA Systems" },
    { id: 337, org: "GHM engineering Group, Inc." },
    { id: 338, org: "Cllimalux S.A." },
    { id: 339, org: "VAISALA Oyj" },
    { id: 340, org: "COMPLEX (Beijing) Technology, Co., LTD." },
    { id: 341, org: "SCADAmetrics" },
    { id: 342, org: "POWERPEG NSI Limited" },
    { id: 343, org: "BACnet Interoperability Testing Services, Inc." },
    { id: 344, org: "Teco a.s." },
    { id: 345, org: "Plexus Technology, Inc." },
    { id: 346, org: "Energy Focus, Inc." },
    { id: 347, org: "Powersmiths International Corp." },
    { id: 348, org: "Nichibei Co., Ltd." },
    { id: 349, org: "HKC Technology Ltd." },
    { id: 350, org: "Ovation Networks, Inc." },
    { id: 351, org: "Setra Systems" },
    { id: 352, org: "AVG Automation" },
    { id: 353, org: "ZXC Ltd." },
    { id: 354, org: "Byte Sphere" },
    { id: 355, org: "Generiton Co., Ltd." },
    { id: 356, org: "Holter Regelarmaturen GmbH & Co. KG" },
    { id: 357, org: "Bedford Instruments, LLC" },
    { id: 358, org: "Standair Inc." },
    { id: 359, org: "WEG Automation – R&D" },
    { id: 360, org: "Prolon Control Systems ApS" },
    { id: 361, org: "Inneasoft" },
    { id: 362, org: "ConneXSoft GmbH" },
    { id: 363, org: "CEAG Notlichtsysteme GmbH" },
    { id: 364, org: "Distech Controls Inc." },
    { id: 365, org: "Industrial Technology Research Institute" },
    { id: 366, org: "Mitsubishi Electric Iconics Digital Solutions" },
    { id: 367, org: "IQ Controls s.c." },
    { id: 368, org: "OJ Electronics A/S" },
    { id: 369, org: "Rolbit Ltd." },
    { id: 370, org: "Synapsys Solutions Ltd." },
    { id: 371, org: "ACME Engineering Prod. Ltd." },
    { id: 372, org: "Zener Electric Pty, Ltd." },
    { id: 373, org: "Selectronix, Inc." },
    { id: 374, org: "Gorbet & Banerjee, LLC." },
    { id: 375, org: "IME" },
    { id: 376, org: "Stephen H. Dawson Computer Service" },
    { id: 377, org: "Accutrol, LLC" },
    { id: 378, org: "Schneider Elektronik GmbH" },
    { id: 379, org: "Alpha-Inno Tec GmbH" },
    { id: 380, org: "ADMMicro, Inc." },
    { id: 381, org: "Greystone Energy Systems, Inc." },
    { id: 382, org: "CAP Technologie" },
    { id: 383, org: "KeRo Systems" },
    { id: 384, org: "Domat Control System s.r.o." },
    { id: 385, org: "Efektronics Pty. Ltd." },
    { id: 386, org: "Hekatron Vertriebs GmbH" },
    { id: 387, org: "Securiton AG" },
    { id: 388, org: "Carlo Gavazzi Controls SpA" },
    { id: 389, org: "Chipkin Automation Systems" },
    { id: 390, org: "Savant Systems, LLC" },
    { id: 391, org: "Simmtronic Lighting Controls" },
    { id: 392, org: "Abelko Innovation AB" },
    { id: 393, org: "Seresco Technologies Inc." },
    { id: 394, org: "IT Watchdogs" },
    { id: 395, org: "Automation Assist Japan Corp." },
    { id: 396, org: "Thermokon Sensortechnik GmbH" },
    { id: 397, org: "EGauge Systems, LLC" },
    { id: 398, org: "Quantum Automation (ASIA) PTE, Ltd." },
    { id: 399, org: "Toshiba Lighting & Technology Corp." },
    { id: 400, org: "SPIN Engenharia de Automação Ltda." },
    { id: 401, org: "Logistics Systems & Software Services India PVT. Ltd." },
    { id: 402, org: "Delta Controls Integration Products" },
    { id: 403, org: "Focus Media" },
    { id: 404, org: "LUMEnergi Inc." },
    { id: 405, org: "Kara Systems" },
    { id: 406, org: "RF Code, Inc." },
    { id: 407, org: "Fatek Automation Corp." },
    { id: 408, org: "JANDA Software Company, LLC" },
    { id: 409, org: "Open System Solutions Limited" },
    { id: 410, org: "Intelec Systems PTY Ltd." },
    { id: 411, org: "Ecolodgix, LLC" },
    { id: 412, org: "Douglas Lighting Controls" },
    { id: 413, org: "iSAtech GmbH" },
    { id: 414, org: "AREAL" },
    { id: 415, org: "Beckhoff Automation" },
    { id: 416, org: "IPAS GmbH" },
    { id: 417, org: "KE2 Therm Solutions" },
    { id: 418, org: "Base2Products" },
    { id: 419, org: "DTL Controls, LLC" },
    { id: 420, org: "INNCOM International, Inc." },
    { id: 421, org: "METZ CONNECT GmbH" },
    { id: 422, org: "Greentrol Automation, Inc" },
    { id: 423, org: "BELIMO Automation AG" },
    { id: 424, org: "Samsung Heavy Industries Co, Ltd" },
    { id: 425, org: "Triacta Power Technologies, Inc." },
    { id: 426, org: "Globestar Systems" },
    { id: 427, org: "MLB Advanced Media, LP" },
    { id: 428, org: "SWG Stuckmann Wirtschaftliche Gebäudesysteme GmbH" },
    { id: 429, org: "SensorSwitch" },
    { id: 430, org: "Multitek Power Limited" },
    { id: 431, org: "Integra Metering AG" },
    { id: 432, org: "LG Electronics Inc." },
    { id: 433, org: "Electronic Theatre Controls, Inc." },
    { id: 434, org: "Mitsubishi Electric Corporation Nagoya Works" },
    { id: 435, org: "Delta Electronics, Inc." },
    { id: 436, org: "Elma Kurtalj, Ltd." },
    { id: 437, org: "Tyco Fire & Security GmbH" },
    { id: 438, org: "Nedap Security Management" },
    { id: 439, org: "ESC Automation Inc." },
    { id: 440, org: "DSP4YOU Ltd." },
    { id: 441, org: "GE Sensing and Inspection Technologies" },
    { id: 442, org: "Embedded Systems SIA" },
    { id: 443, org: "BEFEGA GmbH" },
    { id: 444, org: "Baseline Inc." },
    { id: 445, org: "Key2Act" },
    { id: 446, org: "OEMCtrl" },
    { id: 447, org: "Clarkson Controls Limited" },
    { id: 448, org: "Rogerwell Control System Limited" },
    { id: 449, org: "SCL Elements" },
    { id: 450, org: "Hitachi Ltd." },
    { id: 451, org: "Newron System SA" },
    { id: 452, org: "BEVECO Gebouwautomatisering BV" },
    { id: 453, org: "Streamside Solutions" },
    { id: 454, org: "Yellowstone Soft" },
    { id: 455, org: "Oztech Intelligent Systems Pty Ltd." },
    { id: 456, org: "Novelan GmbH" },
    { id: 457, org: "Flexim Americas Corporation" },
    { id: 458, org: "ICP DAS Co., Ltd." },
    { id: 459, org: "CARMA Industries Inc." },
    { id: 460, org: "Log-One Ltd." },
    { id: 461, org: "TECO Electric & Machinery Co., Ltd." },
    { id: 462, org: "ConnectEx, Inc." },
    { id: 463, org: "Turbo DDC Südwest" },
    { id: 464, org: "Quatrosense Environmental Ltd." },
    { id: 465, org: "Fifth Light Technology Ltd." },
    { id: 466, org: "Scientific Solutions, Ltd." },
    { id: 467, org: "Controller Area Network Solutions (M) Sdn Bhd" },
    { id: 468, org: "RESOL – Elektronische Regelungen GmbH" },
    { id: 469, org: "RPBUS LLC" },
    { id: 470, org: "BRS Sistemas Eletronicos" },
    { id: 471, org: "WindowMaster A/S" },
    { id: 472, org: "Sunlux Technologies Ltd." },
    { id: 473, org: "Measurlogic" },
    { id: 474, org: "Frimat GmbH" },
    { id: 475, org: "Spirax Sarco" },
    { id: 476, org: "Luxtron" },
    { id: 477, org: "Raypak Inc" },
    { id: 478, org: "Air Monitor Corporation" },
    { id: 479, org: "Regler Och Webbteknik Sverige (ROWS)" },
    { id: 480, org: "Intelligent Lighting Controls Inc." },
    { id: 481, org: "Sanyo Electric Industry Co., Ltd" },
    { id: 482, org: "E-Mon Energy Monitoring Products" },
    { id: 483, org: "Digital Control Systems" },
    { id: 484, org: "ATI Airtest Technologies, Inc." },
    { id: 485, org: "SCS SA" },
    { id: 486, org: "HMS Industrial Networks AB" },
    { id: 487, org: "Shenzhen Universal Intellisys Co Ltd" },
    { id: 488, org: "EK Intellisys Sdn Bhd" },
    { id: 489, org: "SysCom" },
    { id: 490, org: "Firecom, Inc." },
    { id: 491, org: "ESA Elektroschaltanlagen Grimma GmbH" },
    { id: 492, org: "Kumahira Co Ltd" },
    { id: 493, org: "Hotraco" },
    { id: 494, org: "SABO Elektronik GmbH" },
    { id: 495, org: "Equip’Trans" },
    { id: 496, org: "Temperature Control Specialities Co., Inc (TCS)" },
    { id: 497, org: "FlowCon International A/S" },
    { id: 498, org: "ThyssenKrupp Elevator Americas" },
    { id: 499, org: "Abatement Technologies" },
    { id: 500, org: "Continental Control Systems, LLC" },
    { id: 501, org: "WISAG Automatisierungstechnik GmbH & Co KG" },
    { id: 502, org: "EasyIO" },
    { id: 503, org: "EAP-Electric GmbH" },
    { id: 504, org: "Hardmeier" },
    { id: 505, org: "Mircom Group of Companies" },
    { id: 506, org: "Quest Controls" },
    { id: 507, org: "Mestek, Inc" },
    { id: 508, org: "Pulse Energy" },
    { id: 509, org: "Tachikawa Corporation" },
    { id: 510, org: "University of Nebraska-Lincoln" },
    { id: 511, org: "Redwood Systems" },
    { id: 512, org: "PASStec Industrie-Elektronik GmbH" },
    { id: 513, org: "NgEK, Inc." },
    { id: 514, org: "t-mac Technologies" },
    { id: 515, org: "Jireh Energy Tech Co., Ltd." },
    { id: 516, org: "Enlighted Inc." },
    { id: 517, org: "El-Piast Sp. Z o.o" },
    { id: 518, org: "NetxAutomation Software GmbH" },
    { id: 519, org: "Invertek Drives" },
    { id: 520, org: "Deutschmann Automation GmbH & Co. KG" },
    { id: 521, org: "EMU Electronic AG" },
    { id: 522, org: "Phaedrus Limited" },
    { id: 523, org: "Sigmatek GmbH & Co KG" },
    { id: 524, org: "Marlin Controls" },
    { id: 525, org: "Circutor, SA" },
    { id: 526, org: "UTC Fire & Security" },
    { id: 527, org: "DENT Instruments, Inc." },
    { id: 528, org: "FHP Manufacturing Company – Bosch Group" },
    { id: 529, org: "GE Intelligent Platforms" },
    { id: 530, org: "Inner Range Pty Ltd" },
    { id: 531, org: "GLAS Energy Technology" },
    { id: 532, org: "MSR-Electronic-GmbH" },
    { id: 533, org: "Energy Control Systems, Inc." },
    { id: 534, org: "EMT Controls" },
    { id: 535, org: "Daintree" },
    { id: 536, org: "EURO ICC d.o.o" },
    { id: 537, org: "TE Connectivity Energy" },
    { id: 538, org: "GEZE GmbH" },
    { id: 539, org: "NEC Corporation" },
    { id: 540, org: "Ho Cheung International Company Limited" },
    { id: 541, org: "Sharp Manufacturing Systems Corporation" },
    { id: 542, org: "DOT CONTROLS a.s." },
    { id: 543, org: "BeaconMedæs" },
    { id: 544, org: "Midea Commercial Aircon" },
    { id: 545, org: "AAON" },
    { id: 546, org: "Kamstrup A/S" },
    { id: 547, org: "CA Computer Automation GmbH" },
    { id: 548, org: "Laars Heating Systems Company" },
    { id: 549, org: "Hitachi Systems, Ltd." },
    { id: 550, org: "Fushan AKE Electronic Engineering Co., Ltd." },
    { id: 551, org: "Toshiba International Corporation" },
    { id: 552, org: "Starman Systems, LLC" },
    { id: 553, org: "Samsung Techwin Co., Ltd." },
    { id: 554, org: "ISAS-Integrated Switchgear and Systems P/L" },
    { id: 555, org: "Reserved for ASHRAE", reserved: true },
    { id: 556, org: "Obvius" },
    { id: 557, org: "Marek Guzik" },
    { id: 558, org: "Vortek Instruments, LLC" },
    { id: 559, org: "Universal Lighting Technologies" },
    { id: 560, org: "Myers Power Products, Inc." },
    { id: 561, org: "Vector Controls GmbH" },
    { id: 562, org: "Crestron Electronics, Inc." },
    { id: 563, org: "A&E Controls Limited" },
    { id: 564, org: "Projektomontaza A.D." },
    { id: 565, org: "Freeaire Refrigeration" },
    { id: 566, org: "Aqua Cooler Pty Limited" },
    { id: 567, org: "Basic Controls" },
    { id: 568, org: "GE Measurement and Control Solutions Advanced Sensors" },
    { id: 569, org: "EQUAL Networks" },
    { id: 570, org: "Millennial Net" },
    { id: 571, org: "APLI Ltd" },
    { id: 572, org: "Electro Industries/GaugeTech" },
    { id: 573, org: "SangMyung University" },
    { id: 574, org: "Coppertree Analytics, Inc." },
    { id: 575, org: "CoreNetiX GmbH" },
    { id: 576, org: "Acutherm" },
    { id: 577, org: "Dr. Riedel Automatisierungstechnik GmbH" },
    { id: 578, org: "Shina System Co., Ltd" },
    { id: 579, org: "Iqapertus" },
    { id: 580, org: "PSE Technology" },
    { id: 581, org: "BA Systems" },
    { id: 582, org: "BTICINO" },
    { id: 583, org: "Monico, Inc." },
    { id: 584, org: "iCue" },
    { id: 585, org: "tekmar Control Systems Ltd." },
    { id: 586, org: "Control Technology Corporation" },
    { id: 587, org: "GFAE GmbH" },
    { id: 588, org: "BeKa Software GmbH" },
    { id: 589, org: "Isoil Industria SpA" },
    { id: 590, org: "Home Systems Consulting SpA" },
    { id: 591, org: "Socomec" },
    { id: 592, org: "Everex Communications, Inc." },
    { id: 593, org: "CET Electric Technology, Inc." },
    { id: 594, org: "Atrila GmbH" },
    { id: 595, org: "WingTechs" },
    { id: 596, org: "Shenzhen Mek Intellisys Pte Ltd." },
    { id: 597, org: "Nestfield Co., Ltd." },
    { id: 598, org: "Swissphone Telecom AG" },
    { id: 599, org: "PNTECH JSC" },
    { id: 600, org: "Horner APG, LLC" },
    { id: 601, org: "PVI Industries, LLC" },
    { id: 602, org: "Ela-compil" },
    { id: 603, org: "Pegasus Automation International LLC" },
    { id: 604, org: "Wight Electronic Services Ltd." },
    { id: 605, org: "Marcom" },
    { id: 606, org: "Exhausto A/S" },
    { id: 607, org: "Dwyer Instruments, Inc." },
    { id: 608, org: "Link GmbH" },
    { id: 609, org: "Oppermann Regelgerate GmbH" },
    { id: 610, org: "NuAire, Inc." },
    { id: 611, org: "Nortec Humidity, Inc." },
    { id: 612, org: "Bigwood Systems, Inc." },
    { id: 613, org: "Enbala Power Networks" },
    { id: 614, org: "Inter Energy Co., Ltd." },
    { id: 615, org: "ETC" },
    { id: 616, org: "COMELEC S.A.R.L" },
    { id: 617, org: "Pythia Technologies" },
    { id: 618, org: "TrendPoint Systems, Inc." },
    { id: 619, org: "AWEX" },
    { id: 620, org: "Eurevia" },
    { id: 621, org: "Kongsberg E-lon AS" },
    { id: 622, org: "FlaktWoods" },
    { id: 623, org: "E + E Elektronik GES M.B.H." },
    { id: 624, org: "ARC Informatique" },
    { id: 625, org: "SKIDATA AG" },
    { id: 626, org: "WSW Solutions" },
    { id: 627, org: "Trefon Electronic GmbH" },
    { id: 628, org: "Dongseo System" },
    { id: 629, org: "Kanontec Intelligence Technology Co., Ltd." },
    { id: 630, org: "EVCO S.p.A." },
    { id: 631, org: "Accuenergy (Canada) Inc." },
    { id: 632, org: "SoftDEL" },
    { id: 633, org: "Orion Energy Systems, Inc." },
    { id: 634, org: "Roboticsware" },
    { id: 635, org: "DOMIQ Sp. z o.o." },
    { id: 636, org: "Solidyne" },
    { id: 637, org: "Elecsys Corporation" },
    { id: 638, org: "Conditionaire International Pty. Limited" },
    { id: 639, org: "Quebec, Inc." },
    { id: 640, org: "Homerun Holdings" },
    { id: 641, org: "Murata Americas" },
    { id: 642, org: "Comptek" },
    { id: 643, org: "Westco Systems, Inc." },
    { id: 644, org: "Advancis Software & Services GmbH" },
    { id: 645, org: "Intergrid, LLC" },
    { id: 646, org: "Markerr Controls, Inc." },
    { id: 647, org: "Toshiba Elevator and Building Systems Corporation" },
    { id: 648, org: "Spectrum Controls, Inc." },
    { id: 649, org: "Mkservice" },
    { id: 650, org: "Fox Thermal Instruments" },
    { id: 651, org: "SyxthSense Ltd" },
    { id: 652, org: "DUHA System S R.O." },
    { id: 653, org: "NIBE" },
    { id: 654, org: "Melink Corporation" },
    { id: 655, org: "Fritz-Haber-Institut" },
    { id: 656, org: "MTU Onsite Energy GmbH, Gas Power Systems" },
    { id: 657, org: "Omega Engineering, Inc." },
    { id: 658, org: "Avelon" },
    { id: 659, org: "Ywire Technologies, Inc." },
    { id: 660, org: "M.R. Engineering Co., Ltd." },
    { id: 661, org: "Lochinvar, LLC" },
    { id: 662, org: "Sontay Limited" },
    { id: 663, org: "GRUPA Slawomir Chelminski" },
    { id: 664, org: "Arch Meter Corporation" },
    { id: 665, org: "Senva, Inc." },
    { id: 666, org: "Reserved for ASHRAE", reserved: true },
    { id: 667, org: "FM-Tec" },
    { id: 668, org: "Systems Specialists, Inc." },
    { id: 669, org: "SenseAir" },
    { id: 670, org: "AB IndustrieTechnik Srl" },
    { id: 671, org: "Cortland Research, LLC" },
    { id: 672, org: "MediaView" },
    { id: 673, org: "VDA Elettronica" },
    { id: 674, org: "CSS, Inc." },
    { id: 675, org: "Tek-Air Systems, Inc." },
    { id: 676, org: "ICDT" },
    { id: 677, org: "The Armstrong Monitoring Corporation" },
    { id: 678, org: "DIXELL S.r.l" },
    { id: 679, org: "Lead System, Inc." },
    { id: 680, org: "ISM EuroCenter S.A." },
    { id: 681, org: "TDIS" },
    { id: 682, org: "Trade FIDES" },
    { id: 683, org: "Knürr GmbH (Emerson Network Power)" },
    { id: 684, org: "Resource Data Management" },
    { id: 685, org: "Abies Technology, Inc." },
    { id: 686, org: "UAB Komfovent" },
    { id: 687, org: "MIRAE Electrical Mfg. Co., Ltd." },
    { id: 688, org: "HunterDouglas Architectural Projects Scandinavia ApS" },
    { id: 689, org: "RUNPAQ Group Co., Ltd" },
    { id: 690, org: "Unicard SA" },
    { id: 691, org: "IE Technologies" },
    { id: 692, org: "Ruskin Manufacturing" },
    { id: 693, org: "Calon Associates Limited" },
    { id: 694, org: "Contec Co., Ltd." },
    { id: 695, org: "iT GmbH" },
    { id: 696, org: "Autani Corporation" },
    { id: 697, org: "Christian Fortin" },
    { id: 698, org: "HDL" },
    { id: 699, org: "IPID Sp. Z.O.O Limited" },
    { id: 700, org: "Fuji Electric Co., Ltd" },
    { id: 701, org: "View, Inc." },
    { id: 702, org: "Samsung S1 Corporation" },
    { id: 703, org: "New Lift" },
    { id: 704, org: "VRT Systems" },
    { id: 705, org: "Motion Control Engineering, Inc." },
    { id: 706, org: "Weiss Klimatechnik GmbH" },
    { id: 707, org: "Elkon" },
    { id: 708, org: "Eliwell Controls S.r.l." },
    { id: 709, org: "Japan Computer Technos Corp" },
    { id: 710, org: "Rational Network ehf" },
    { id: 711, org: "Magnum Energy Solutions, LLC" },
    { id: 712, org: "MelRok" },
    { id: 713, org: "VAE Group" },
    { id: 714, org: "LGCNS" },
    { id: 715, org: "Berghof Automationstechnik GmbH" },
    { id: 716, org: "Quark Communications, Inc." },
    { id: 717, org: "Sontex" },
    { id: 718, org: "mivune AG" },
    { id: 719, org: "Panduit" },
    { id: 720, org: "Smart Controls, LLC" },
    { id: 721, org: "Compu-Aire, Inc." },
    { id: 722, org: "Sierra" },
    { id: 723, org: "ProtoSense Technologies" },
    { id: 724, org: "Eltrac Technologies Pvt Ltd" },
    { id: 725, org: "Bektas Invisible Controls GmbH" },
    { id: 726, org: "Entelec" },
    { id: 727, org: "INNEXIV" },
    { id: 728, org: "Covenant" },
    { id: 729, org: "Davitor AB" },
    { id: 730, org: "TongFang Technovator" },
    { id: 731, org: "Building Robotics, Inc." },
    { id: 732, org: "HSS-MSR UG" },
    { id: 733, org: "FramTack LLC" },
    { id: 734, org: "B. L. Acoustics, Ltd." },
    { id: 735, org: "Traxxon Rock Drills, Ltd" },
    { id: 736, org: "Franke" },
    { id: 737, org: "Wurm GmbH & Co" },
    { id: 738, org: "AddENERGIE" },
    { id: 739, org: "Mirle Automation Corporation" },
    { id: 740, org: "Ibis Networks" },
    { id: 741, org: "ID-KARTA s.r.o." },
    { id: 742, org: "Anaren, Inc." },
    { id: 743, org: "Span, Incorporated" },
    { id: 744, org: "Bosch Thermotechnology Corp" },
    { id: 745, org: "DRC Technology S.A." },
    { id: 746, org: "Shanghai Energy Building Technology Co, Ltd" },
    { id: 747, org: "Fraport AG" },
    { id: 748, org: "Flowgroup" },
    { id: 749, org: "Skytron Energy, GmbH" },
    { id: 750, org: "ALTEL Wicha, Golda Sp. J." },
    { id: 751, org: "Drupal" },
    { id: 752, org: "Axiomatic Technology, Ltd" },
    { id: 753, org: "Bohnke + Partner" },
    { id: 754, org: "Function1" },
    { id: 755, org: "Optergy Pty, Ltd" },
    { id: 756, org: "LSI Virticus" },
    { id: 757, org: "Konzeptpark GmbH" },
    { id: 758, org: "NX Lighting Controls" },
    { id: 759, org: "eCurv, Inc." },
    { id: 760, org: "Agnosys GmbH" },
    { id: 761, org: "Shanghai Sunfull Automation Co., LTD" },
    { id: 762, org: "Kurz Instruments, Inc." },
    { id: 763, org: "Cias Elettronica S.r.l." },
    { id: 764, org: "Multiaqua, Inc." },
    { id: 765, org: "BlueBox" },
    { id: 766, org: "Sensidyne" },
    { id: 767, org: "Viessmann Elektronik GmbH" },
    { id: 768, org: "ADFweb.com srl" },
    { id: 769, org: "Gaylord Industries" },
    { id: 770, org: "Majur Ltd." },
    { id: 771, org: "Shanghai Huilin Technology Co., Ltd." },
    { id: 772, org: "Exotronic" },
    { id: 773, org: "SAFECONTROL s.r.o." },
    { id: 774, org: "Amatis" },
    { id: 775, org: "Universal Electric Corporation" },
    { id: 776, org: "iBACnet" },
    { id: 777, org: "Reserved for ASHRAE", reserved: true },
    { id: 778, org: "Smartrise Engineering, Inc." },
    { id: 779, org: "Miratron, Inc." },
    { id: 780, org: "SmartEdge" },
    { id: 781, org: "Mitsubishi Electric Australia Pty Ltd" },
    { id: 782, org: "Triangle Research International Ptd Ltd" },
    { id: 783, org: "Produal Oy" },
    { id: 784, org: "Milestone Systems A/S" },
    { id: 785, org: "Trustbridge" },
    { id: 786, org: "Feedback Solutions" },
    { id: 787, org: "IES" },
    { id: 788, org: "ABB Power Protection SA" },
    { id: 789, org: "Riptide IO" },
    { id: 790, org: "Messerschmitt Systems AG" },
    { id: 791, org: "Dezem Energy Controlling" },
    { id: 792, org: "MechoSystems" },
    { id: 793, org: "evon GmbH" },
    { id: 794, org: "CS Lab GmbH" },
    { id: 795, org: "8760 Enterprises, Inc." },
    { id: 796, org: "Touche Controls" },
    { id: 797, org: "Ontrol Teknik Malzeme San. ve Tic. A.S." },
    { id: 798, org: "Uni Control System Sp. Z o.o." },
    { id: 799, org: "Weihai Ploumeter Co., Ltd" },
    { id: 800, org: "Elcom International Pvt. Ltd" },
    { id: 801, org: "Signify" },
    { id: 802, org: "AutomationDirect" },
    { id: 803, org: "Paragon Robotics" },
    { id: 804, org: "SMT System & Modules Technology AG" },
    { id: 805, org: "Radix IoT LLC" },
    { id: 806, org: "CMR Controls Ltd" },
    { id: 807, org: "Innovari, Inc." },
    { id: 808, org: "ABB Control Products" },
    { id: 809, org: "Gesellschaft fur Gebäudeautomation mbH" },
    { id: 810, org: "RODI Systems Corp." },
    { id: 811, org: "Nextek Power Systems" },
    { id: 812, org: "Creative Lighting" },
    { id: 813, org: "WaterFurnace International" },
    { id: 814, org: "Mercury Security" },
    { id: 815, org: "Hisense (Shandong) Air-Conditioning Co., Ltd." },
    { id: 816, org: "Layered Solutions, Inc." },
    { id: 817, org: "Leegood Automatic System, Inc." },
    { id: 818, org: "Shanghai Restar Technology Co., Ltd." },
    { id: 819, org: "Reimann Ingenieurbüro" },
    { id: 820, org: "LynTec" },
    { id: 821, org: "HTP" },
    { id: 822, org: "Elkor Technologies, Inc." },
    { id: 823, org: "Bentrol Pty Ltd" },
    { id: 824, org: "Team-Control Oy" },
    { id: 825, org: "NextDevice, LLC" },
    { id: 826, org: "iSMA CONTROLLI S.p.a." },
    { id: 827, org: "King I Electronics Co., Ltd" },
    { id: 828, org: "SAMDAV" },
    { id: 829, org: "Next Gen Industries Pvt. Ltd." },
    { id: 830, org: "Entic LLC" },
    { id: 831, org: "ETAP" },
    { id: 832, org: "Moralle Electronics Limited" },
    { id: 833, org: "Leicom AG" },
    { id: 834, org: "Watts Regulator Company" },
    { id: 835, org: "S.C. Orbtronics S.R.L." },
    { id: 836, org: "Gaussan Technologies" },
    { id: 837, org: "WEBfactory GmbH" },
    { id: 838, org: "Ocean Controls" },
    { id: 839, org: "Messana Air-Ray Conditioning s.r.l." },
    { id: 840, org: "Hangzhou BATOWN Technology Co. Ltd." },
    { id: 841, org: "Reasonable Controls" },
    { id: 842, org: "Servisys, Inc." },
    { id: 843, org: "halstrup-walcher GmbH" },
    { id: 844, org: "SWG Automation Fuzhou Limited" },
    { id: 845, org: "KSB Aktiengesellschaft" },
    { id: 846, org: "Hybryd Sp. z o.o." },
    { id: 847, org: "Helvatron AG" },
    { id: 848, org: "Oderon Sp. Z.O.O." },
    { id: 849, org: "mikolab" },
    { id: 850, org: "Exodraft" },
    { id: 851, org: "Hochhuth GmbH" },
    { id: 852, org: "Integrated System Technologies Ltd." },
    { id: 853, org: "Shanghai Cellcons Controls Co., Ltd" },
    { id: 854, org: "Emme Controls, LLC" },
    { id: 855, org: "Field Diagnostic Services, Inc." },
    { id: 856, org: "Ges Teknik A.S." },
    { id: 857, org: "Global Power Products, Inc." },
    { id: 858, org: "Option NV" },
    { id: 859, org: "BV-Control AG" },
    { id: 860, org: "Sigren Engineering AG" },
    { id: 861, org: "Shanghai Jaltone Technology Co., Ltd." },
    { id: 862, org: "MaxLine Solutions Ltd" },
    { id: 863, org: "Kron Instrumentos Elétricos Ltda" },
    { id: 864, org: "Thermo Matrix" },
    { id: 865, org: "Infinite Automation Systems, Inc." },
    { id: 866, org: "Vantage" },
    { id: 867, org: "Elecon Measurements Pvt Ltd" },
    { id: 868, org: "TBA" },
    { id: 869, org: "Carnes Company" },
    { id: 870, org: "Harman Professional" },
    { id: 871, org: "Nenutec Asia Pacific Pte Ltd" },
    { id: 872, org: "Gia NV" },
    { id: 873, org: "Kepware Tehnologies" },
    { id: 874, org: "Temperature Electronics Ltd" },
    { id: 875, org: "Packet Power" },
    { id: 876, org: "Project Haystack Corporation" },
    { id: 877, org: "DEOS Controls Americas Inc." },
    { id: 878, org: "Senseware Inc" },
    { id: 879, org: "MST Systemtechnik AG" },
    { id: 880, org: "Lonix Ltd" },
    { id: 881, org: "Gossen Metrawatt GmbH" },
    { id: 882, org: "Aviosys International Inc." },
    { id: 883, org: "Efficient Building Automation Corp." },
    { id: 884, org: "Accutron Instruments Inc." },
    { id: 885, org: "Vermont Energy Control Systems LLC" },
    { id: 886, org: "DCC Dynamics" },
    { id: 887, org: "B.E.G. Brück Electronic GmbH" },
    { id: 888, org: "Reserved for ASHRAE", reserved: true },
    { id: 889, org: "NGBS Hungary Ltd." },
    { id: 890, org: "ILLUM Technology, LLC" },
    { id: 891, org: "Delta Controls Germany Limited" },
    { id: 892, org: "S+T Service & Technique S.A." },
    { id: 893, org: "SimpleSoft" },
    { id: 894, org: "Altair Engineering" },
    { id: 895, org: "EZEN Solution Inc." },
    { id: 896, org: "Fujitec Co. Ltd." },
    { id: 897, org: "Terralux" },
    { id: 898, org: "Annicom" },
    { id: 899, org: "Bihl+Wiedemann GmbH" },
    { id: 900, org: "Draper, Inc." },
    { id: 901, org: "Schüco International KG" },
    { id: 902, org: "Otis Elevator Company" },
    { id: 903, org: "Fidelix Oy" },
    { id: 904, org: "RAM GmbH Mess- und Regeltechnik" },
    { id: 905, org: "WEMS" },
    { id: 906, org: "Ravel Electronics Pvt Ltd" },
    { id: 907, org: "OmniMagni" },
    { id: 908, org: "Echelon" },
    { id: 909, org: "Intellimeter Canada, Inc." },
    { id: 910, org: "Bithouse Oy" },
    { id: 911, org: "Reserved for ASHRAE", reserved: true },
    { id: 912, org: "BuildPulse" },
    { id: 913, org: "Shenzhen 1000 Building Automation Co. Ltd" },
    { id: 914, org: "AED Engineering GmbH" },
    { id: 915, org: "Güntner GmbH & Co. KG" },
    { id: 916, org: "KNXlogic" },
    { id: 917, org: "CIM Environmental Group" },
    { id: 918, org: "Flow Control" },
    { id: 919, org: "Lumen Cache, Inc." },
    { id: 920, org: "Ecosystem" },
    { id: 921, org: "Potter Electric Signal Company, LLC" },
    { id: 922, org: "Tyco Fire & Security S.p.A." },
    { id: 923, org: "Watanabe Electric Industry Co., Ltd." },
    { id: 924, org: "Causam Energy" },
    { id: 925, org: "W-tec AG" },
    { id: 926, org: "IMI Hydronic Engineering International SA" },
    { id: 927, org: "ARIGO Software" },
    { id: 928, org: "MSA Safety" },
    { id: 929, org: "Smart Solucoes Ltda – MERCATO" },
    { id: 930, org: "PIATRA Engineering" },
    { id: 931, org: "ODIN Automation Systems, LLC" },
    { id: 932, org: "Belparts NV" },
    { id: 933, org: "UAB, SALDA" },
    { id: 934, org: "Alre-IT Regeltechnik GmbH" },
    { id: 935, org: "Ingenieurbüro H. Lertes GmbH & Co. KG" },
    { id: 936, org: "Breathing Buildings" },
    { id: 937, org: "eWON SA" },
    { id: 938, org: "Cav. Uff. Giacomo Cimberio S.p.A" },
    { id: 939, org: "PKE Software Solutions GmbH" },
    { id: 940, org: "Allen" },
    { id: 941, org: "Kastle Systems" },
    { id: 942, org: "Logical Electro-Mechanical (EM) Systems, Inc." },
    { id: 943, org: "ppKinetics Instruments, LLC" },
    { id: 944, org: "Cathexis Technologies" },
    { id: 945, org: "Sylop sp. Z o.o. sp.k" },
    { id: 946, org: "Brauns Control GmbH" },
    { id: 947, org: "OMRON SOCIAL SOLUTIONS CO., LTD." },
    { id: 948, org: "Wildeboer Bauteile Gmbh" },
    { id: 949, org: "Shanghai Biens Technologies Ltd" },
    { id: 950, org: "Beijing HZHY Technology Co., Ltd" },
    { id: 951, org: "Building Clouds" },
    { id: 952, org: "The University of Sheffield-Department of Electronic and Electrical Engineering" },
    { id: 953, org: "Fabtronics Australia Pty Ltd" },
    { id: 954, org: "SLAT" },
    { id: 955, org: "Software Motor Corporation" },
    { id: 956, org: "Armstrong International Inc." },
    { id: 957, org: "Steril-Aire, Inc." },
    { id: 958, org: "Infinique" },
    { id: 959, org: "Arcom" },
    { id: 960, org: "Argo Performance, Ltd" },
    { id: 961, org: "Dialight" },
    { id: 962, org: "Ideal Technical Solutions" },
    { id: 963, org: "Neurobat AG" },
    { id: 964, org: "Neyer Software Consulting LLC" },
    { id: 965, org: "SCADA Technology Development Co., Ltd." },
    { id: 966, org: "Demand Logic Limited" },
    { id: 967, org: "GWA Group Limited" },
    { id: 968, org: "Occitaline" },
    { id: 969, org: "NAO Digital Co., Ltd." },
    { id: 970, org: "Shenzhen Chanslink Network Technology Co., Ltd." },
    { id: 971, org: "Samsung Electronics Co., Ltd." },
    { id: 972, org: "Mesa Laboratories, Inc." },
    { id: 973, org: "Fischer" },
    { id: 974, org: "OpSys Solutions Ltd." },
    { id: 975, org: "Advanced Devices Limited" },
    { id: 976, org: "Condair" },
    { id: 977, org: "INELCOM Ingenieria Electronica Comercial S.A." },
    { id: 978, org: "GridPoint, Inc." },
    { id: 979, org: "ADF Technologies Sdn Bhd" },
    { id: 980, org: "EPM, Inc." },
    { id: 981, org: "Lighting Controls Ltd" },
    { id: 982, org: "Perix Controls Ltd." },
    { id: 983, org: "AERCO International, Inc." },
    { id: 984, org: "KONE Inc." },
    { id: 985, org: "Ziehl-Abegg SE" },
    { id: 986, org: "Robot, S.A." },
    { id: 987, org: "Optigo Networks, Inc." },
    { id: 988, org: "Openmotics BVBA" },
    { id: 989, org: "Metropolitan Industries, Inc." },
    { id: 990, org: "Huawei Technologies Co., Ltd." },
    { id: 991, org: "Digital Lumens, Inc." },
    { id: 992, org: "Vanti" },
    { id: 993, org: "Cree Lighting" },
    { id: 994, org: "Richmond Heights SDN BHD" },
    { id: 995, org: "Payne-Sparkman Lighting Mangement" },
    { id: 996, org: "Ashcroft" },
    { id: 997, org: "Jet Controls Corp" },
    { id: 998, org: "Zumtobel Lighting GmbH" },
    { id: 999, org: "Reserved for ASHRAE", reserved: true },
    { id: 1000, org: "Ekon GmbH" },
    { id: 1001, org: "Molex" },
    { id: 1002, org: "Maco Lighting Pty Ltd." },
    { id: 1003, org: "Axecon Corp." },
    { id: 1004, org: "Tensor plc" },
    { id: 1005, org: "Kaseman Environmental Control Equipment (Shanghai) Limited" },
    { id: 1006, org: "AB Axis Industries" },
    { id: 1007, org: "Netix Controls" },
    { id: 1008, org: "Eldridge Products, Inc." },
    { id: 1009, org: "Micronics" },
    { id: 1010, org: "Fortecho Solutions Ltd" },
    { id: 1011, org: "Sellers Manufacturing Company" },
    { id: 1012, org: "Rite-Hite Doors, Inc." },
    { id: 1013, org: "Violet Defense LLC" },
    { id: 1014, org: "Simna" },
    { id: 1015, org: "Multi-Énergie Best Inc." },
    { id: 1016, org: "Mega System Technologies, Inc." },
    { id: 1017, org: "Rheem" },
    { id: 1018, org: "Ing. Punzenberger COPA-DATA GmbH" },
    { id: 1019, org: "MEC Electronics GmbH" },
    { id: 1020, org: "Taco Comfort Solutions" },
    { id: 1021, org: "Alexander Maier GmbH" },
    { id: 1022, org: "Ecorithm, Inc." },
    { id: 1023, org: "Accurro Ltd" },
    { id: 1024, org: "ROMTECK Australia Pty Ltd" },
    { id: 1025, org: "Splash Monitoring Limited" },
    { id: 1026, org: "Light Application" },
    { id: 1027, org: "Logical Building Automation" },
    { id: 1028, org: "Exilight Oy" },
    { id: 1029, org: "Hager Electro SAS" },
    { id: 1030, org: "KLIF Co., LTD" },
    { id: 1031, org: "HygroMatik" },
    { id: 1032, org: "Daniel Mousseau Programmation & Electronique" },
    { id: 1033, org: "Aerionics Inc." },
    { id: 1034, org: "M2S Electronique Ltee" },
    { id: 1035, org: "Automation Components, Inc." },
    { id: 1036, org: "Niobrara Research & Development Corporation" },
    { id: 1037, org: "Netcom Sicherheitstechnik GmbH" },
    { id: 1038, org: "Lumel S.A." },
    { id: 1039, org: "Great Plains Industries, Inc." },
    { id: 1040, org: "Domotica Labs S.R.L" },
    { id: 1041, org: "Energy Cloud, Inc." },
    { id: 1042, org: "Vomatec" },
    { id: 1043, org: "Demma Companies" },
    { id: 1044, org: "Valsena" },
    { id: 1045, org: "Comsys Bärtsch AG" },
    { id: 1046, org: "bGrid" },
    { id: 1047, org: "MDJ Software Pty Ltd" },
    { id: 1048, org: "Dimonoff, Inc." },
    { id: 1049, org: "Edomo Systems, GmbH" },
    { id: 1050, org: "Effektiv, LLC" },
    { id: 1051, org: "SteamOVap" },
    { id: 1052, org: "grandcentrix GmbH" },
    { id: 1053, org: "Weintek Labs, Inc." },
    { id: 1054, org: "Intefox GmbH" },
    { id: 1055, org: "Radius22 Automation Company" },
    { id: 1056, org: "Ringdale, Inc." },
    { id: 1057, org: "Iwaki America" },
    { id: 1058, org: "Bractlet" },
    { id: 1059, org: "STULZ Air Technology Systems, Inc." },
    { id: 1060, org: "Climate Ready Engineering Pty Ltd" },
    { id: 1061, org: "Genea Energy Partners" },
    { id: 1062, org: "IoTall Chile" },
    { id: 1063, org: "IKS Co., Ltd." },
    { id: 1064, org: "Yodiwo AB" },
    { id: 1065, org: "TITAN electronic GmbH" },
    { id: 1066, org: "IDEC Corporation" },
    { id: 1067, org: "SIFRI SL" },
    { id: 1068, org: "Thermal Gas Systems Inc." },
    { id: 1069, org: "Building Automation Products, Inc." },
    { id: 1070, org: "Asset Mapping" },
    { id: 1071, org: "Smarteh Company" },
    { id: 1072, org: "Datapod (Australia) Pty Ltd." },
    { id: 1073, org: "Buildings Alive Pty Ltd" },
    { id: 1074, org: "Digital Elektronik" },
    { id: 1075, org: "Talent Automação e Tecnologia Ltda" },
    { id: 1076, org: "Norposh Limited" },
    { id: 1077, org: "Merkur Funksysteme AG" },
    { id: 1078, org: "Faster CZ spol. S.r.o" },
    { id: 1079, org: "Eco-Adapt" },
    { id: 1080, org: "Energocentrum Plus, s.r.o" },
    { id: 1081, org: "amBX UK Ltd" },
    { id: 1082, org: "Western Reserve Controls, Inc." },
    { id: 1083, org: "LayerZero Power Systems, Inc." },
    { id: 1084, org: "CIC Jan Hřebec s.r.o." },
    { id: 1085, org: "Sigrov BV" },
    { id: 1086, org: "ISYS-Intelligent Systems" },
    { id: 1087, org: "Gas Detection (Australia) Pty Ltd" },
    { id: 1088, org: "Kinco Automation (Shanghai) Ltd." },
    { id: 1089, org: "Lars Energy, LLC" },
    { id: 1090, org: "Flamefast (UK) Ltd." },
    { id: 1091, org: "Royal Service Air Conditioning" },
    { id: 1092, org: "Ampio Sp. Z o.o." },
    { id: 1093, org: "Inovonics Wireless Corporation" },
    { id: 1094, org: "Nvent Thermal Management" },
    { id: 1095, org: "Sinowell Control System Ltd" },
    { id: 1096, org: "Moxa Inc." },
    { id: 1097, org: "Matrix iControl SDN BHD" },
    { id: 1098, org: "PurpleSwift" },
    { id: 1099, org: "OTIM Technologies" },
    { id: 1100, org: "FlowMate Limited" },
    { id: 1101, org: "Degree Controls, Inc." },
    { id: 1102, org: "Fei Xing (Shanghai) Software Technologies Co., Ltd." },
    { id: 1103, org: "Berg GmbH" },
    { id: 1104, org: "ARENZ.IT" },
    { id: 1105, org: "Edelstrom Electronic Devices & Designing LLC" },
    { id: 1106, org: "Drive Connect, LLC" },
    { id: 1107, org: "DevelopNow" },
    { id: 1108, org: "Poort" },
    { id: 1109, org: "VMEIL Information (Shanghai) Ltd" },
    { id: 1110, org: "Rayleigh Instruments" },
    { id: 1111, org: "Reserved for ASHRAE", reserved: true },
    { id: 1112, org: "CODESYS Development" },
    { id: 1113, org: "Smartware Technologies Group, LLC" },
    { id: 1114, org: "Polar Bear Solutions" },
    { id: 1115, org: "Codra" },
    { id: 1116, org: "Pharos Architectural Controls Ltd" },
    { id: 1117, org: "EngiNear Ltd." },
    { id: 1118, org: "Ad Hoc Electronics" },
    { id: 1119, org: "Unified Microsystems" },
    { id: 1120, org: "Industrieelektronik Brandenburg GmbH" },
    { id: 1121, org: "Hartmann GmbH" },
    { id: 1122, org: "Piscada" },
    { id: 1123, org: "KMB systems, s.r.o." },
    { id: 1124, org: "PowerTech Engineering AS" },
    { id: 1125, org: "Telefonbau Arthur Schwabe GmbH & Co. KG" },
    { id: 1126, org: "Wuxi Fistwelove Technology Co., Ltd." },
    { id: 1127, org: "Prysm" },
    { id: 1128, org: "STEINEL GmbH" },
    { id: 1129, org: "Georg Fischer JRG AG" },
    { id: 1130, org: "Make Develop SL" },
    { id: 1131, org: "Monnit Corporation" },
    { id: 1132, org: "Mirror Life Corporation" },
    { id: 1133, org: "Secure Meters Limited" },
    { id: 1134, org: "PECO" },
    { id: 1135, org: ".CCTECH, Inc." },
    { id: 1136, org: "LightFi Limited" },
    { id: 1137, org: "Nice Spa" },
    { id: 1138, org: "Fiber SenSys, Inc." },
    { id: 1139, org: "B&D Buchta und Degeorgi" },
    { id: 1140, org: "Ventacity Systems, Inc." },
    { id: 1141, org: "Hitachi-Johnson Controls Air Conditioning, Inc." },
    { id: 1142, org: "Sage Metering, Inc." },
    { id: 1143, org: "Andel Limited" },
    { id: 1144, org: "ECOSmart Technologies" },
    { id: 1145, org: "S.E.T." },
    { id: 1146, org: "Protec Fire Detection Spain SL" },
    { id: 1147, org: "AGRAMER UG" },
    { id: 1148, org: "Anylink Electronic GmbH" },
    { id: 1149, org: "Schindler, Ltd" },
    { id: 1150, org: "Jibreel Abdeen Est." },
    { id: 1151, org: "Fluidyne Control Systems Pvt. Ltd" },
    { id: 1152, org: "Prism Systems, Inc." },
    { id: 1153, org: "Enertiv" },
    { id: 1154, org: "Mirasoft GmbH & Co. KG" },
    { id: 1155, org: "DUALTECH IT" },
    { id: 1156, org: "Countlogic, LLC" },
    { id: 1157, org: "Kohler" },
    { id: 1158, org: "Chen Sen Controls Co., Ltd." },
    { id: 1159, org: "Greenheck" },
    { id: 1160, org: "Intwine Connect, LLC" },
    { id: 1161, org: "Karlborgs Elkontroll" },
    { id: 1162, org: "Datakom" },
    { id: 1163, org: "Hoga Control AS" },
    { id: 1164, org: "Cool Automation" },
    { id: 1165, org: "Inter Search Co., Ltd" },
    { id: 1166, org: "DABBEL-Automation Intelligence GmbH" },
    { id: 1167, org: "Gadgeon Engineering Smartness" },
    { id: 1168, org: "Coster Group S.r.l." },
    { id: 1169, org: "Walter Müller AG" },
    { id: 1170, org: "Fluke" },
    { id: 1171, org: "Quintex Systems Ltd" },
    { id: 1172, org: "Senfficient SDN BHD" },
    { id: 1173, org: "Nube iO Operations Pty Ltd" },
    { id: 1174, org: "DAS Integrator Pte Ltd" },
    { id: 1175, org: "CREVIS Co., Ltd" },
    { id: 1176, org: "iSquared software inc." },
    { id: 1177, org: "KTG GmbH" },
    { id: 1178, org: "POK Group Oy" },
    { id: 1179, org: "Adiscom" },
    { id: 1180, org: "Incusense" },
    { id: 1181, org: "75F" },
    { id: 1182, org: "Anord Mardix, Inc." },
    { id: 1183, org: "HOSCH Gebäudeautomation Neue Produkte GmbH" },
    { id: 1184, org: "Bosch.IO GmbH" },
    { id: 1185, org: "Royal Boon Edam International B.V." },
    { id: 1186, org: "Clack Corporation" },
    { id: 1187, org: "Unitex Controls LLC" },
    { id: 1188, org: "KTC Göteborg AB" },
    { id: 1189, org: "Interzon AB" },
    { id: 1190, org: "ISDE ING SL" },
    { id: 1191, org: "ABM automation building messaging GmbH" },
    { id: 1192, org: "Kentec Electronics Ltd" },
    { id: 1193, org: "Copeland LP" },
    { id: 1194, org: "Powerside" },
    { id: 1195, org: "SMC Group" },
    { id: 1196, org: "EOS Weather Instruments" },
    { id: 1197, org: "Zonex Systems" },
    { id: 1198, org: "Generex Systems Computervertriebsgesellschaft mbH" },
    { id: 1199, org: "Energy Wall LLC" },
    { id: 1200, org: "Thermofin" },
    { id: 1201, org: "SDATAWAY SA" },
    { id: 1202, org: "Biddle Air Systems Limited" },
    { id: 1203, org: "Kessler Ellis Products" },
    { id: 1204, org: "Thermoscreens" },
    { id: 1205, org: "Modio" },
    { id: 1206, org: "Newron Solutions" },
    { id: 1207, org: "Unitronics" },
    { id: 1208, org: "TRILUX GmbH & Co. KG" },
    { id: 1209, org: "Kollmorgen Steuerungstechnik GmbH" },
    { id: 1210, org: "Bosch Rexroth AG" },
    { id: 1211, org: "Alarko Carrier" },
    { id: 1212, org: "Verdigris Technologies" },
    { id: 1213, org: "Shanghai SIIC-Longchuang Smartech So., Ltd." },
    { id: 1214, org: "Quinda Co." },
    { id: 1215, org: "GRUNER AG" },
    { id: 1216, org: "BACMOVE" },
    { id: 1217, org: "PSIDAC AB" },
    { id: 1218, org: "ISICON-Control Automation" },
    { id: 1219, org: "Big Ass Fans" },
    { id: 1220, org: "din – Dietmar Nocker Facility Management GmbH" },
    { id: 1221, org: "Teldio" },
    { id: 1222, org: "MIKROKLIMA s.r.o." },
    { id: 1223, org: "Density" },
    { id: 1224, org: "ICONAG-Leittechnik GmbH" },
    { id: 1225, org: "Awair" },
    { id: 1226, org: "T&D Engineering, Ltd" },
    { id: 1227, org: "Sistemas Digitales" },
    { id: 1228, org: "Loxone Electronics GmbH" },
    { id: 1229, org: "ActronAir" },
    { id: 1230, org: "Inductive Automation" },
    { id: 1231, org: "Thor Engineering GmbH" },
    { id: 1232, org: "Berner International, LLC" },
    { id: 1233, org: "Potsdam Sensors LLC" },
    { id: 1234, org: "Kohler Mira Ltd" },
    { id: 1235, org: "Tecomon GmbH" },
    { id: 1236, org: "Two Dimensional Instruments, LLC" },
    { id: 1237, org: "LEFA Technologies Pte. Ltd." },
    { id: 1238, org: "EATON CEAG Notlichtsysteme GmbH" },
    { id: 1239, org: "Commbox Tecnologia" },
    { id: 1240, org: "IPVideo Corporation" },
    { id: 1241, org: "Bender GmbH & Co. KG" },
    { id: 1242, org: "Rhymebus Corporation" },
    { id: 1243, org: "Axon Systems Ltd" },
    { id: 1244, org: "Engineered Air" },
    { id: 1245, org: "Elipse Software Ltda" },
    { id: 1246, org: "Simatix Building Technologies Pvt. Ltd." },
    { id: 1247, org: "W.A. Benjamin Electric Co." },
    { id: 1248, org: "TROX Air Conditioning Components (Suzhou) Co. Ltd." },
    { id: 1249, org: "SC Medical Pty Ltd." },
    { id: 1250, org: "Elcanic A/S" },
    { id: 1251, org: "Obeo AS" },
    { id: 1252, org: "Tapa, Inc." },
    { id: 1253, org: "ASE Smart Energy, Inc." },
    { id: 1254, org: "Performance Services, Inc." },
    { id: 1255, org: "Veridify Security" },
    { id: 1256, org: "CD Innovation LTD" },
    { id: 1257, org: "Ben Peoples Industries, LLC" },
    { id: 1258, org: "UNICOMM Sp. z o.o" },
    { id: 1259, org: "Thing Technologies GmbH" },
    { id: 1260, org: "Beijing Hailin Control Technology, Inc." },
    { id: 1261, org: "Digital Realty" },
    { id: 1262, org: "Agrowtek Inc." },
    { id: 1263, org: "DSP Innovation BV" },
    { id: 1264, org: "STV Electronic GmbH" },
    { id: 1265, org: "Elmeasure India Pvt Ltd." },
    { id: 1266, org: "Pineshore Energy LLC" },
    { id: 1267, org: "Brasch Environmental Technologies, LLC" },
    { id: 1268, org: "ShenZhen ZhiXing Building Tech Co., Ltd" },
    { id: 1269, org: "Sinux" },
    { id: 1270, org: "Avnet Inc." },
    { id: 1271, org: "Somfy Activites SA" },
    { id: 1272, org: "Amico" },
    { id: 1273, org: "SageGlass" },
    { id: 1274, org: "AuVerte" },
    { id: 1275, org: "Agile Connects Pvt. Ltd." },
    { id: 1276, org: "Locimation Pty Ltd" },
    { id: 1277, org: "Envio Systems GmbH" },
    { id: 1278, org: "Voytech Systems Limited" },
    { id: 1279, org: "Davidsmeyer und Paul GmbH" },
    { id: 1280, org: "Lusher Engineering Services" },
    { id: 1281, org: "CHNT Nanjing Techsel Intelligent Company LTD" },
    { id: 1282, org: "Threetronics Pty Ltd" },
    { id: 1283, org: "SkyFoundry, LLC" },
    { id: 1284, org: "HanilProTech" },
    { id: 1285, org: "Sensorscall" },
    { id: 1286, org: "Shanghai Jingpu Information Technology, Co., Ltd." },
    { id: 1287, org: "Lichtmanufaktur Berlin GmbH" },
    { id: 1288, org: "Eco Parking Technologies" },
    { id: 1289, org: "Envision Digital International Pte Ltd" },
    { id: 1290, org: "Antony Developpement Electronique" },
    { id: 1291, org: "i2systems" },
    { id: 1292, org: "Thureon International Limited" },
    { id: 1293, org: "Pulsafeeder" },
    { id: 1294, org: "MegaChips Corporation" },
    { id: 1295, org: "TES Controls" },
    { id: 1296, org: "Cermate" },
    { id: 1297, org: "Grand Valley State University" },
    { id: 1298, org: "Symcon Gmbh" },
    { id: 1299, org: "The Chicago Faucet Company" },
    { id: 1300, org: "Geberit AG" },
    { id: 1301, org: "Rex Controls" },
    { id: 1302, org: "IVMS GmbH" },
    { id: 1303, org: "MNPP Saturn Ltd." },
    { id: 1304, org: "Regal Beloit" },
    { id: 1305, org: "ACS-Air Conditioning Solutions" },
    { id: 1306, org: "GBX Technology, LLC" },
    { id: 1307, org: "Kaiterra" },
    { id: 1308, org: "ThinKuan loT Technology (Shanghai) Co., Ltd" },
    { id: 1309, org: "HoCoSto B.V." },
    { id: 1310, org: "Shenzhen AS-AI Technology Co., Ltd." },
    { id: 1311, org: "RPS S.p.a." },
    { id: 1312, org: "Esmé solutions" },
    { id: 1313, org: "IOTech Systems Limited" },
    { id: 1314, org: "i-AutoLogic Co., Ltd." },
    { id: 1315, org: "New Age Micro, LLC" },
    { id: 1316, org: "Guardian Glass" },
    { id: 1317, org: "Guangzhou Zhaoyu Information Technology" },
    { id: 1318, org: "ACE IoT Solutions LLC" },
    { id: 1319, org: "Poris Electronics Co., Ltd." },
    { id: 1320, org: "Terminus Technologies Group" },
    { id: 1321, org: "Intech 21, Inc." },
    { id: 1322, org: "Accurate Electronics" },
    { id: 1323, org: "Fluence Bioengineering" },
    { id: 1324, org: "Mun Hean Singapore Pte Ltd" },
    { id: 1325, org: "Katronic AG & Co. KG" },
    { id: 1326, org: "Suzhou XinAo Information Technology Co. Ltd" },
    { id: 1327, org: "Linktekk Technology, JSC." },
    { id: 1328, org: "Stirling Ultracold" },
    { id: 1329, org: "UV Partners, Inc." },
    { id: 1330, org: "ProMinent GmbH" },
    { id: 1331, org: "Multi-Tech Systems, Inc." },
    { id: 1332, org: "JUMO GmbH & Co. KG" },
    { id: 1333, org: "Qingdao Huarui Technology Co. Ltd.," },
    { id: 1334, org: "Cairn Systemes" },
    { id: 1335, org: "NeuroLogic Research Corp." },
    { id: 1336, org: "Transition Technologies Advanced Solutions Sp. z o.o" },
    { id: 1337, org: "Xxter bv" },
    { id: 1338, org: "PassiveLogic" },
    { id: 1339, org: "EnSmart Controls" },
    { id: 1340, org: "Watts Heating and Hot Water Solutions, dba Lync" },
    { id: 1341, org: "Troposphaira Technologies LLP" },
    { id: 1342, org: "Network Thermostat" },
    { id: 1343, org: "Titanium Intelligent Solutions, LLC" },
    { id: 1344, org: "Numa Products, LLC" },
    { id: 1345, org: "WAREMA Renkhoff SE" },
    { id: 1346, org: "Frese A/S" },
    { id: 1347, org: "Mapped" },
    { id: 1348, org: "ELEKTRODESIGN ventilatory s.r.o" },
    { id: 1349, org: "AirCare Automation, Inc." },
    { id: 1350, org: "Antrum" },
    { id: 1351, org: "Bao Linh Connect Technology" },
    { id: 1352, org: "Virginia Controls, LLC" },
    { id: 1353, org: "Duosys SDN BHD" },
    { id: 1354, org: "Onsen SAS" },
    { id: 1355, org: "Vaughn Thermal Corporation" },
    { id: 1356, org: "Thermoplastic Engineering Ltd (TPE)" },
    { id: 1357, org: "Wirth Research Ltd." },
    { id: 1358, org: "SST Automation" },
    { id: 1359, org: "Shanghai Bencol Electronic Technology Co., Ltd" },
    { id: 1360, org: "AIWAA Systems Private Limited" },
    { id: 1361, org: "Enless Wireless" },
    { id: 1362, org: "Ozuno Engineering Pty Ltd" },
    { id: 1363, org: "Hubbell, The Electric Heater Company" },
    { id: 1364, org: "Industrial Turnaround Corporation (ITAC)" },
    { id: 1365, org: "Wadsworth Control Systems" },
    { id: 1366, org: "Services Hilo Inc." },
    { id: 1367, org: "iDM Energiesysteme GmbH" },
    { id: 1368, org: "BeNext B.V." },
    { id: 1369, org: "CleanAir.ai Corporation" },
    { id: 1370, org: "Revolution Microelectronics (America) Inc." },
    { id: 1371, org: "Real-Time Systems GmbH" },
    { id: 1372, org: "ZedBee Technologies Pvt Ltd" },
    { id: 1373, org: "Wimate Technology Solutions Pvt. Ltd." },
    { id: 1374, org: "Senticon Ltd." },
    { id: 1375, org: "Rossaker AB" },
    { id: 1376, org: "OPIT Solutions Ltd" },
    { id: 1377, org: "Hotowell International Co., Limited" },
    { id: 1378, org: "Inim Electronics S.R.L. Unipersonale" },
    { id: 1379, org: "Airthings ASA" },
    { id: 1380, org: "Analog Devices, Inc." },
    { id: 1381, org: "AIDirections DMCC" },
    { id: 1382, org: "Prima Electro S.p.A." },
    { id: 1383, org: "KLT Control System Ltd." },
    { id: 1384, org: "Evolution Controls Inc." },
    { id: 1385, org: "Bever Innovations" },
    { id: 1386, org: "Pelican Wireless Systems" },
    { id: 1387, org: "Control Concepts Inc." },
    { id: 1388, org: "Augmatic Technologies Pvt. Ltd." },
    { id: 1389, org: "Xiamen Milesight loT Co., Ltd" },
    { id: 1390, org: "Tianjin Anjie loT Schience and Technology Co., Ltd" },
    { id: 1391, org: "Guangzhou S. Energy Electronics Technology Co. Ltd." },
    { id: 1392, org: "AKVO Atmospheric Water Systems Pvt. Ltd." },
    { id: 1393, org: "EmFirst Co. Ltd." },
    { id: 1394, org: "Iion Systems ApS" },
    { id: 1396, org: "SAF Tehnika JSC" },
    { id: 1397, org: "Komfort IQ, Inc." },
    { id: 1398, org: "CoolTera Limited" },
    { id: 1399, org: "Hadron Solutions S.r.l.s" },
    { id: 1401, org: "Bitpool" },
    { id: 1402, org: "Sonicu, LLC" },
    { id: 1403, org: "Rishabh Instruments Limited" },
    { id: 1404, org: "Thing Warehouse LLC" },
    { id: 1405, org: "Innofriends GmbH" },
    { id: 1406, org: "Metronic AKP Sp. J." },
    { id: 1407, org: "Techknave" },
    { id: 1408, org: "Elsner Elektronik" },
    { id: 1409, org: "LEFOO Industrial (Hangzhou) Co., Ltd." },
    { id: 1410, org: "Calibration Technologies, Inc." },
    { id: 1411, org: "Allorado" },
    { id: 1412, org: "Verkada" },
    { id: 1413, org: "Wattsense" },
    { id: 1414, org: "Emerson Automation Solutions" },
    { id: 1415, org: "Growlink" },
    { id: 1416, org: "Olympia Electronics" },
    { id: 1417, org: "Normal Software, Inc." },
    { id: 1418, org: "ST Engineering Solution JSC" },
    { id: 1419, org: "Industrial Flow Solutions" },
    { id: 1420, org: "Ubiqisense ApS" },
    { id: 1421, org: "Tiger-Soft" },
    { id: 1422, org: "Ecodom Srl" },
    { id: 1423, org: "Bilgipro IoT Systems" },
    { id: 1424, org: "planspur netdesign GmbH" },
    { id: 1425, org: "Dolphin Solutions Ltd" },
    { id: 1426, org: "Mitsubishi Electric Corporation, Kobe Works" },
    { id: 1427, org: "Ecovena" },
    { id: 1428, org: "Gree Electric Appliances Inc of Zhuhai" },
    { id: 1429, org: "Conspec Controls" },
    { id: 1430, org: "Hangzhou Hikvision Digital Technology Co., Ltd." },
    { id: 1431, org: "Crystal Peak Security" },
    { id: 1432, org: "PermAlert" },
    { id: 1433, org: "Zhejiang Misilin Technology Co., Ltd." },
    { id: 1434, org: "Dekker Vacuum Technologies" },
    { id: 1435, org: "Edwards Limited" },
    { id: 1436, org: "Leybold GmbH" },
    { id: 1437, org: "International Gas Detectors" },
    { id: 1438, org: "Atlas Copco Airpower NV" },
    { id: 1439, org: "Air Sentry Limited" },
    { id: 1440, org: "Aelsys" },
    { id: 1441, org: "Granby Consulting LLC" },
    { id: 1442, org: "Clever Relay" },
    { id: 1443, org: "Monico Monitoring, Inc." },
    { id: 1444, org: "Oqdo" },
    { id: 1445, org: "Matrix Comsec Private Limited" },
    { id: 1446, org: "Resource Solutions" },
    { id: 1447, org: "American Gas Safety, LLC" },
    { id: 1448, org: "S&S Northern Ltd." },
    { id: 1449, org: "Ulbios Techsens" },
    { id: 1450, org: "Bowery Farming, Inc." },
    { id: 1451, org: "Ryobi Limited" },
    { id: 1452, org: "EkkoSense Ltd" },
    { id: 1453, org: "ClimaCool" },
    { id: 1454, org: "Grid Connect Inc." },
    { id: 1455, org: "Ziegler Instrumentation UK Ltd" },
    { id: 1456, org: "ControlTec, LLC" },
    { id: 1457, org: "Aeterlink Corporation" },
    { id: 1458, org: "Alpha Epsilon Automation" },
    { id: 1459, org: "Astralite Inc." },
    { id: 1460, org: "Delta Fire Ltda." },
    { id: 1461, org: "Bock Water Heaters, Inc." },
    { id: 1462, org: "Cleaver-Brooks" },
    { id: 1463, org: "Scanalytics, Inc." },
    { id: 1464, org: "WI6LABS" },
    { id: 1465, org: "AC&T System Co., Ltd" },
    { id: 1466, org: "VergeSense" },
    { id: 1467, org: "Systemair Mfg. Inc." },
    { id: 1468, org: "Seeley International" },
    { id: 1469, org: "Crane Building Services & Utilities" },
    { id: 1470, org: "Brady Corporation" },
    { id: 1471, org: "Qingdao Hisense Hitachi Air-Conditioning Systems Co., Ltd." },
    { id: 1472, org: "Golden Quality Co. Ltd." },
    { id: 1473, org: "Elvaco AB" },
    { id: 1474, org: "Strong Technology, LLC" },
    { id: 1475, org: "REC Environmental Technology (Guangzhou) Company Limited" },
    { id: 1476, org: "Disruptive Technologies Research AS" },
    { id: 1477, org: "Nico Consultancy Limited" },
    { id: 1478, org: "Horten lot (Jiangsu) Co., Ltd." },
    { id: 1479, org: "Paxton Controls Corp." },
    { id: 1480, org: "Fell Technology AS" },
    { id: 1481, org: "SHLOK Information Systems India Private Limited" },
    { id: 1482, org: "Microgro PLC Ltd." },
    { id: 1483, org: "Clouder Oy" },
    { id: 1484, org: "Gebäude Automatisierung GmbH" },
    { id: 1485, org: "solvimus GmbH" },
    { id: 1486, org: "GuangZhou Wangkong Ltd." },
    { id: 1487, org: "SafeSquare GmbH" },
    { id: 1488, org: "Heklatech AB" },
    { id: 1489, org: "Silvair" },
    { id: 1490, org: "Adveco" },
    { id: 1491, org: "Eura Drives Electric Co., Ltd." },
    { id: 1492, org: "Caleb Controls" },
    { id: 1493, org: "InBiot Monitoring S.L" },
    { id: 1494, org: "Qingdao Haier Air Conditioner Electric Co., Ltd." },
    { id: 1495, org: "Hangzhou Weiyl Technology Co., Ltd." },
    { id: 1496, org: "yord sàrl" },
    { id: 1497, org: "Infinitum Electric" },
    { id: 1498, org: "Red Bean Systems Limited" },
    { id: 1499, org: "Blue Time Concept SA" },
    { id: 1500, org: "Shenzhen INVT Electric Co., Ltd." },
    { id: 1501, org: "Messung Systems Pvt Ltd." },
    { id: 1502, org: "ABB Electrification Canada Inc." },
    { id: 1503, org: "Core Controls" },
    { id: 1504, org: "Noord Tech d.o.o." },
    { id: 1505, org: "Varibits AS" },
    { id: 1506, org: "Roger Sp. z o.o. sp.k." },
    { id: 1507, org: "Viega GmbH & Co. KG" },
    { id: 1508, org: "Astersoft" },
    { id: 1509, org: "BIG-EU" },
    { id: 1510, org: "Inferrix Limited" },
    { id: 1511, org: "Richards Electric Motor Co." },
    { id: 1512, org: "dAPPControls" },
    { id: 1513, org: "Entouch Controls" },
    { id: 1514, org: "Mavili Elektronik Ticaret ve Sanayi Anonim Sirketi" },
    { id: 1515, org: "BubblyNet" },
    { id: 1516, org: "AlMayssan Technical Services Co. Ltd." },
    { id: 1517, org: "Viridi Parente, Inc." },
    { id: 1518, org: "Novel Apps Corp." },
    { id: 1519, org: "Oventrop (China) HVAC System Technology Co., Ltd." },
    { id: 1521, org: "Lacroix Sofrel" },
    { id: 1522, org: "MachineSens loT Trading Co., LLC" },
    { id: 1523, org: "Elmec Inc." },
    { id: 1524, org: "Beijing Haishi Software Co., Ltd." },
    { id: 1525, org: "Radix Electrosystems Pvt. Ltd." },
    { id: 1526, org: "Värmebaronen AB" },
    { id: 1527, org: "Treau Inc., dba Gradient" },
    { id: 1528, org: "WEST Solution AG" },
    { id: 1529, org: "Trueway Controls Hongkong Limited" },
    { id: 1530, org: "BuildingLogiX" },
    { id: 1531, org: "Ifesca GmbH" },
    { id: 1532, org: "Fellowes Inc." },
    { id: 1533, org: "Caleffi S.p.A." },
    { id: 1534, org: "JDRF Electromag" },
    { id: 1535, org: "Redwire Labs" },
    { id: 1536, org: "Wecon Technology Co., Ltd." },
    { id: 1537, org: "Acacia Green Technologies Ltd" },
    { id: 1538, org: "Degree Analytics" },
    { id: 1539, org: "Roltek Teknoloji A.S." },
    { id: 1540, org: "Digital Control Technology Limited" },
    { id: 1541, org: "Kentima AB" },
    { id: 1542, org: "Pergamon Perceptive Technologies" },
    { id: 1543, org: "Prefect Controls Ltd." },
    { id: 1544, org: "SenTech Corporation" },
    { id: 1545, org: "S+S Regeltechnik GmbH" },
    { id: 1546, org: "AirBox, Inc." },
    { id: 1547, org: "RVE" },
    { id: 1548, org: "Motorola Solutions" },
    { id: 1549, org: "BACSYS Innovations Private Limited" },
    { id: 1550, org: "Ewattch" },
    { id: 1551, org: "Builtlayer LLC" },
    { id: 1552, org: "A&G Domotix S.R.L." },
    { id: 1553, org: "Hytronik Industrial Limited" },
    { id: 1554, org: "WHO Reinraumtechnik" },
    { id: 1555, org: "TRICO Limited" },
    { id: 1556, org: "SLKAutomation SRL" },
    { id: 1557, org: "Zaphire AS" },
    { id: 1558, org: "AJ Manufacturing" },
    { id: 1559, org: "Future Motors Ltd." },
    { id: 1560, org: "Himel Hong Kong Limited" },
    { id: 1561, org: "Shenzhen Sunricher Technology Co., Ltd." },
    { id: 1562, org: "Actility S.A." },
    { id: 1563, org: "Oy Halton Group Ltd." },
    { id: 1564, org: "AVTECH Software, Inc." },
    { id: 1565, org: "InControl Engineering LLC" },
    { id: 1566, org: "SoundWater Technologies LLC" },
    { id: 1567, org: "Circular Bv" },
    { id: 1568, org: "Normatic AS" },
    { id: 1569, org: "Dock Rd" },
    { id: 1570, org: "SmartD Technologies Inc." },
    { id: 1571, org: "Line of Sight Services LLC" },
    { id: 1572, org: "LAIIER Ltd." },
    { id: 1573, org: "Antec Controls" },
    { id: 1574, org: "CG Conception" },
    { id: 1575, org: "Shanghai YuanKong Automation Technology Co., Ltd." },
    { id: 1576, org: "Armatura LLC" },
    { id: 1577, org: "Ingy BV" },
    { id: 1578, org: "Heartful Code" },
    { id: 1579, org: "System Mart Ltd." },
    { id: 1580, org: "Spot7 GmbH" },
    { id: 1581, org: "Intempco Controls Ltd." },
    { id: 1582, org: "Rosemont Engineering, Inc." },
    { id: 1583, org: "Miniveil Industries Ltd." },
    { id: 1584, org: "Profcon AB" },
    { id: 1585, org: "KE Automasjon AS" },
    { id: 1586, org: "Nordomatic Property Technologies AB" },
    { id: 1587, org: "Runwise" },
    { id: 1588, org: "Karel Čavojsky" },
    { id: 1589, org: "ABB LV Installation Materials Co., Ltd. Beijing" },
    { id: 1590, org: "EnerSearch Solar GmbH" },
    { id: 1591, org: "Zurn Elkay Water Solutions" },
    { id: 1592, org: "Andivi" },
    { id: 1593, org: "Chyi Lee Industry Co., Ltd." },
    { id: 1594, org: "Allbee B.V." },
    { id: 1595, org: "Kampmann GmbH & Co. KG" },
    { id: 1596, org: "Cosel Elektronik Otomasyon Sistemleri San. Tic. Ltd. Sti." },
    { id: 1597, org: "Ractl Designs" },
    { id: 1598, org: "Databridge Dynamic Pvt Ltd" },
    { id: 1599, org: "Evolo Technologies AS" },
    { id: 1600, org: "EnergyPlus Teknoloji Imalat Ithalat ve Ihracat Sanayi AS" },
    { id: 1601, org: "Gaiamesh Inc." },
    { id: 1602, org: "Lovato Electric S.P.A." },
    { id: 1603, org: "Q-PAC Systems, Inc." },
    { id: 1604, org: "Yobiiq Intelligence B.V." },
    { id: 1605, org: "Camfil USA Inc." },
    { id: 1606, org: "Radnox" },
    { id: 1607, org: "Optospark Sdn. Bhd." },
    { id: 1608, org: "Controlbright" },
    { id: 1609, org: "Pentair Residential Filtration" },
    { id: 1610, org: "Venaera Inc." },
    { id: 1611, org: "HumiPure" },
    { id: 1612, org: "Humber Horizons" },
    { id: 1613, org: "Automated Facility Systems, Inc." },
    { id: 1614, org: "SiteSense AS" },
    { id: 1615, org: "Eco-2i EURL" },
    { id: 1616, org: "Donix Embedded Systems CC" },
    { id: 1617, org: "GPS Air" },
    { id: 1618, org: "–" },
    { id: 1619, org: "Qingping Technology Beijing Co., Ltd." },
    { id: 1620, org: "PSsystec GmbH" },
    { id: 1621, org: "3ES Otomasyon San. Tic. Ltd. Sti." },
    { id: 1622, org: "Network Corporation" },
    { id: 1623, org: "Veawe Info Dynamics Private Limited" },
    { id: 1624, org: "Visual Solutions UK Ltd" },
    { id: 1625, org: "NICOR Lighting" },
    { id: 1626, org: "EME Automation" },
    { id: 1627, org: "ControlCom Technologies, LLC" },
    { id: 1628, org: "ElectrSol" },
    { id: 1629, org: "Corporación Empresarial Altra" },
    { id: 1630, org: "IC Valves (Nanjing) Co., Ltd." },
    { id: 1631, org: "Occuspace Inc." },
];

module.exports = {
    vendors,
    // The IDs ASHRAE holds and never assigns (flagged reserved above).
    reserved: [555, 666, 777, 888, 911, 999, 1111],
    maxId: 1631,
    retrieved: '2026-07-08',
    source: 'https://bacnet.org/assigned-vendor-ids/',
};
