// BACnet engineering units — GENERATED FILE, do not hand-edit.
//
// Source: https://raw.githubusercontent.com/bacnet-stack/bacnet-stack/master/src/bacnet/bacenum.h
//   (bacnet-stack's BACnetEngineeringUnits enum — the de-facto machine-
//    readable form of the ASHRAE 135 Units enumeration, which is paywalled)
// Retrieved: 2026-07-12 · 255 values (0–254) · 79 enriched from bacnetEnums.js
// Regenerate: npm run import-bacnet-units
//   (.github/scripts/import-bacnet-units.mjs — validates before writing)
//
// The full standard Units enumeration (property 117 values). Ids 0–254
// are ASHRAE-standard; 256–65535 is the proprietary/vendor range and
// carries no assigned names here. Where an id also appears in the curated
// bacnetEnums.js slice its name/symbol/group are that row verbatim (canonical
// ASHRAE spelling + editorial symbol/group); long-tail ids take their name
// from the bacnet-stack macro and should be verified against ASHRAE 135
// before being treated as authoritative — the page says as much.
//
// Name strings are site-authored ASCII/Unicode and render with `| safe`,
// same as bacnetEnums.js.

const units = [
    { id: 0, name: "square-meters", symbol: "m²", group: "Length & area" },
    { id: 1, name: "square-feet", symbol: "ft²", group: "Length & area" },
    { id: 2, name: "milliamperes", symbol: "mA", group: "Electrical" },
    { id: 3, name: "amperes", symbol: "A", group: "Electrical" },
    { id: 4, name: "ohms", symbol: "Ω", group: "Electrical" },
    { id: 5, name: "volts", symbol: "V", group: "Electrical" },
    { id: 6, name: "kilovolts" },
    { id: 7, name: "megavolts" },
    { id: 8, name: "volt-amperes", symbol: "VA", group: "Electrical" },
    { id: 9, name: "kilovolt-amperes", symbol: "kVA", group: "Electrical" },
    { id: 10, name: "megavolt-amperes" },
    { id: 11, name: "volt-amperes-reactive", symbol: "var", group: "Electrical" },
    { id: 12, name: "kilovolt-amperes-reactive", symbol: "kvar", group: "Electrical" },
    { id: 13, name: "megavolt-amperes-reactive" },
    { id: 14, name: "degrees-phase" },
    { id: 15, name: "power-factor", group: "Electrical" },
    { id: 16, name: "joules" },
    { id: 17, name: "kilojoules" },
    { id: 18, name: "watt-hours" },
    { id: 19, name: "kilowatt-hours", symbol: "kWh", group: "Energy" },
    { id: 20, name: "btus", symbol: "Btu", group: "Energy" },
    { id: 21, name: "therms", group: "Energy" },
    { id: 22, name: "ton-hours", group: "Energy" },
    { id: 23, name: "joules-per-kilogram-dry-air", symbol: "J/kg", group: "Humidity & enthalpy" },
    { id: 24, name: "btus-per-pound-dry-air", symbol: "Btu/lb", group: "Humidity & enthalpy" },
    { id: 25, name: "cycles-per-hour" },
    { id: 26, name: "cycles-per-minute" },
    { id: 27, name: "hertz", symbol: "Hz", group: "Frequency & speed" },
    { id: 28, name: "grams-of-water-per-kilogram-dry-air", symbol: "g/kg", group: "Humidity & enthalpy" },
    { id: 29, name: "percent-relative-humidity", symbol: "%RH", group: "Humidity & enthalpy" },
    { id: 30, name: "millimeters", symbol: "mm", group: "Length & area" },
    { id: 31, name: "meters", symbol: "m", group: "Length & area" },
    { id: 32, name: "inches", symbol: "in", group: "Length & area" },
    { id: 33, name: "feet", symbol: "ft", group: "Length & area" },
    { id: 34, name: "watts-per-square-foot", symbol: "W/ft²", group: "Power" },
    { id: 35, name: "watts-per-square-meter", symbol: "W/m²", group: "Power" },
    { id: 36, name: "lumens", symbol: "lm", group: "Light" },
    { id: 37, name: "luxes", symbol: "lx", group: "Light" },
    { id: 38, name: "foot-candles", symbol: "fc", group: "Light" },
    { id: 39, name: "kilograms", symbol: "kg", group: "Mass & mass flow" },
    { id: 40, name: "pounds-mass", symbol: "lb", group: "Mass & mass flow" },
    { id: 41, name: "tons" },
    { id: 42, name: "kilograms-per-second" },
    { id: 43, name: "kilograms-per-minute" },
    { id: 44, name: "kilograms-per-hour", symbol: "kg/h", group: "Mass & mass flow" },
    { id: 45, name: "pounds-mass-per-minute", symbol: "lb/min", group: "Mass & mass flow" },
    { id: 46, name: "pounds-mass-per-hour", symbol: "lb/h", group: "Mass & mass flow" },
    { id: 47, name: "watts", symbol: "W", group: "Power" },
    { id: 48, name: "kilowatts", symbol: "kW", group: "Power" },
    { id: 49, name: "megawatts", symbol: "MW", group: "Power" },
    { id: 50, name: "btus-per-hour", symbol: "Btu/h", group: "Power" },
    { id: 51, name: "horsepower", symbol: "hp", group: "Power" },
    { id: 52, name: "tons-refrigeration", symbol: "tons", group: "Power" },
    { id: 53, name: "pascals", symbol: "Pa", group: "Pressure" },
    { id: 54, name: "kilopascals", symbol: "kPa", group: "Pressure" },
    { id: 55, name: "bars", symbol: "bar", group: "Pressure" },
    { id: 56, name: "pounds-force-per-square-inch", symbol: "psi", group: "Pressure" },
    { id: 57, name: "centimeters-of-water" },
    { id: 58, name: "inches-of-water", symbol: "in. w.c.", group: "Pressure" },
    { id: 59, name: "millimeters-of-mercury", symbol: "mmHg", group: "Pressure" },
    { id: 60, name: "centimeters-of-mercury" },
    { id: 61, name: "inches-of-mercury", symbol: "inHg", group: "Pressure" },
    { id: 62, name: "degrees-Celsius", symbol: "°C", group: "Temperature" },
    { id: 63, name: "kelvin", symbol: "K", group: "Temperature" },
    { id: 64, name: "degrees-Fahrenheit", symbol: "°F", group: "Temperature" },
    { id: 65, name: "degree-days-Celsius", group: "Temperature" },
    { id: 66, name: "degree-days-Fahrenheit", group: "Temperature" },
    { id: 67, name: "years" },
    { id: 68, name: "months" },
    { id: 69, name: "weeks" },
    { id: 70, name: "days", group: "Time" },
    { id: 71, name: "hours", symbol: "h", group: "Time" },
    { id: 72, name: "minutes", symbol: "min", group: "Time" },
    { id: 73, name: "seconds", symbol: "s", group: "Time" },
    { id: 74, name: "meters-per-second", symbol: "m/s", group: "Velocity" },
    { id: 75, name: "kilometers-per-hour" },
    { id: 76, name: "feet-per-second" },
    { id: 77, name: "feet-per-minute", symbol: "fpm", group: "Velocity" },
    { id: 78, name: "miles-per-hour" },
    { id: 79, name: "cubic-feet", symbol: "ft³", group: "Volume" },
    { id: 80, name: "cubic-meters", symbol: "m³", group: "Volume" },
    { id: 81, name: "imperial-gallons" },
    { id: 82, name: "liters", symbol: "L", group: "Volume" },
    { id: 83, name: "us-gallons", symbol: "gal", group: "Volume" },
    { id: 84, name: "cubic-feet-per-minute", symbol: "CFM", group: "Flow" },
    { id: 85, name: "cubic-meters-per-second", symbol: "m³/s", group: "Flow" },
    { id: 86, name: "imperial-gallons-per-minute" },
    { id: 87, name: "liters-per-second", symbol: "L/s", group: "Flow" },
    { id: 88, name: "liters-per-minute", symbol: "L/min", group: "Flow" },
    { id: 89, name: "us-gallons-per-minute", symbol: "gpm", group: "Flow" },
    { id: 90, name: "degrees-angular" },
    { id: 91, name: "degrees-Celsius-per-hour" },
    { id: 92, name: "degrees-Celsius-per-minute" },
    { id: 93, name: "degrees-Fahrenheit-per-hour" },
    { id: 94, name: "degrees-Fahrenheit-per-minute" },
    { id: 95, name: "no-units", group: "General" },
    { id: 96, name: "parts-per-million", symbol: "ppm", group: "General" },
    { id: 97, name: "parts-per-billion", symbol: "ppb", group: "General" },
    { id: 98, name: "percent", symbol: "%", group: "General" },
    { id: 99, name: "percent-per-second" },
    { id: 100, name: "per-minute" },
    { id: 101, name: "per-second" },
    { id: 102, name: "psi-per-degree-Fahrenheit" },
    { id: 103, name: "radians" },
    { id: 104, name: "revolutions-per-minute", symbol: "RPM", group: "Frequency & speed" },
    { id: 105, name: "currency1" },
    { id: 106, name: "currency2" },
    { id: 107, name: "currency3" },
    { id: 108, name: "currency4" },
    { id: 109, name: "currency5" },
    { id: 110, name: "currency6" },
    { id: 111, name: "currency7" },
    { id: 112, name: "currency8" },
    { id: 113, name: "currency9" },
    { id: 114, name: "currency10" },
    { id: 115, name: "square-inches" },
    { id: 116, name: "square-centimeters" },
    { id: 117, name: "btus-per-pound" },
    { id: 118, name: "centimeters" },
    { id: 119, name: "pounds-mass-per-second" },
    { id: 120, name: "delta-degrees-Fahrenheit", symbol: "Δ°F", group: "Temperature" },
    { id: 121, name: "delta-kelvin", symbol: "ΔK", group: "Temperature" },
    { id: 122, name: "kilohms", symbol: "kΩ", group: "Electrical" },
    { id: 123, name: "megohms" },
    { id: 124, name: "millivolts" },
    { id: 125, name: "kilojoules-per-kilogram" },
    { id: 126, name: "megajoules" },
    { id: 127, name: "joules-per-degree-kelvin" },
    { id: 128, name: "joules-per-kilogram-degree-kelvin" },
    { id: 129, name: "kilohertz" },
    { id: 130, name: "megahertz" },
    { id: 131, name: "per-hour" },
    { id: 132, name: "milliwatts" },
    { id: 133, name: "hectopascals" },
    { id: 134, name: "millibars" },
    { id: 135, name: "cubic-meters-per-hour", symbol: "m³/h", group: "Flow" },
    { id: 136, name: "liters-per-hour" },
    { id: 137, name: "kw-hours-per-square-meter" },
    { id: 138, name: "kw-hours-per-square-foot" },
    { id: 139, name: "megajoules-per-square-meter" },
    { id: 140, name: "megajoules-per-square-foot" },
    { id: 141, name: "watts-per-square-meter-degree-kelvin" },
    { id: 142, name: "cubic-feet-per-second" },
    { id: 143, name: "percent-obscuration-per-foot" },
    { id: 144, name: "percent-obscuration-per-meter" },
    { id: 145, name: "milliohms" },
    { id: 146, name: "megawatt-hours", symbol: "MWh", group: "Energy" },
    { id: 147, name: "kilo-btus", symbol: "kBtu", group: "Energy" },
    { id: 148, name: "mega-btus" },
    { id: 149, name: "kilojoules-per-kilogram-dry-air" },
    { id: 150, name: "megajoules-per-kilogram-dry-air" },
    { id: 151, name: "kilojoules-per-degree-kelvin" },
    { id: 152, name: "megajoules-per-degree-kelvin" },
    { id: 153, name: "newton" },
    { id: 154, name: "grams-per-second" },
    { id: 155, name: "grams-per-minute" },
    { id: 156, name: "tons-per-hour" },
    { id: 157, name: "kilo-btus-per-hour", symbol: "MBH", group: "Power" },
    { id: 158, name: "hundredths-seconds" },
    { id: 159, name: "milliseconds" },
    { id: 160, name: "newton-meters" },
    { id: 161, name: "millimeters-per-second" },
    { id: 162, name: "millimeters-per-minute" },
    { id: 163, name: "meters-per-minute" },
    { id: 164, name: "meters-per-hour" },
    { id: 165, name: "cubic-meters-per-minute" },
    { id: 166, name: "meters-per-second-per-second" },
    { id: 167, name: "amperes-per-meter" },
    { id: 168, name: "amperes-per-square-meter" },
    { id: 169, name: "ampere-square-meters" },
    { id: 170, name: "farads" },
    { id: 171, name: "henrys" },
    { id: 172, name: "ohm-meters" },
    { id: 173, name: "siemens" },
    { id: 174, name: "siemens-per-meter" },
    { id: 175, name: "teslas" },
    { id: 176, name: "volts-per-degree-kelvin" },
    { id: 177, name: "volts-per-meter" },
    { id: 178, name: "webers" },
    { id: 179, name: "candelas" },
    { id: 180, name: "candelas-per-square-meter" },
    { id: 181, name: "kelvin-per-hour" },
    { id: 182, name: "kelvin-per-minute" },
    { id: 183, name: "joule-seconds" },
    { id: 184, name: "radians-per-second" },
    { id: 185, name: "square-meters-per-newton" },
    { id: 186, name: "kilograms-per-cubic-meter" },
    { id: 187, name: "newton-seconds" },
    { id: 188, name: "newtons-per-meter" },
    { id: 189, name: "watts-per-meter-per-degree-kelvin" },
    { id: 190, name: "microsiemens" },
    { id: 191, name: "cubic-feet-per-hour" },
    { id: 192, name: "us-gallons-per-hour" },
    { id: 193, name: "kilometers" },
    { id: 194, name: "micrometers" },
    { id: 195, name: "grams" },
    { id: 196, name: "milligrams" },
    { id: 197, name: "milliliters" },
    { id: 198, name: "milliliters-per-second" },
    { id: 199, name: "decibels" },
    { id: 200, name: "decibels-millivolt" },
    { id: 201, name: "decibels-volt" },
    { id: 202, name: "millisiemens" },
    { id: 203, name: "watt-reactive-hours" },
    { id: 204, name: "kilowatt-reactive-hours" },
    { id: 205, name: "megawatt-reactive-hours" },
    { id: 206, name: "millimeters-of-water" },
    { id: 207, name: "per-mille" },
    { id: 208, name: "grams-per-gram" },
    { id: 209, name: "kilograms-per-kilogram" },
    { id: 210, name: "grams-per-kilogram" },
    { id: 211, name: "milligrams-per-gram" },
    { id: 212, name: "milligrams-per-kilogram" },
    { id: 213, name: "grams-per-milliliter" },
    { id: 214, name: "grams-per-liter" },
    { id: 215, name: "milligrams-per-liter" },
    { id: 216, name: "micrograms-per-liter" },
    { id: 217, name: "grams-per-cubic-meter" },
    { id: 218, name: "milligrams-per-cubic-meter" },
    { id: 219, name: "micrograms-per-cubic-meter" },
    { id: 220, name: "nanograms-per-cubic-meter" },
    { id: 221, name: "grams-per-cubic-centimeter" },
    { id: 222, name: "becquerels" },
    { id: 223, name: "kilobecquerels" },
    { id: 224, name: "megabecquerels" },
    { id: 225, name: "gray" },
    { id: 226, name: "milligray" },
    { id: 227, name: "microgray" },
    { id: 228, name: "sieverts" },
    { id: 229, name: "millisieverts" },
    { id: 230, name: "microsieverts" },
    { id: 231, name: "microsieverts-per-hour" },
    { id: 232, name: "decibels-a" },
    { id: 233, name: "nephelometric-turbidity-unit" },
    { id: 234, name: "ph" },
    { id: 235, name: "grams-per-square-meter" },
    { id: 236, name: "minutes-per-degree-kelvin" },
    { id: 237, name: "ohm-meter-squared-per-meter" },
    { id: 238, name: "ampere-seconds" },
    { id: 239, name: "volt-ampere-hours" },
    { id: 240, name: "kilovolt-ampere-hours" },
    { id: 241, name: "megavolt-ampere-hours" },
    { id: 242, name: "volt-ampere-reactive-hours" },
    { id: 243, name: "kilovolt-ampere-reactive-hours" },
    { id: 244, name: "megavolt-ampere-reactive-hours" },
    { id: 245, name: "volt-square-hours" },
    { id: 246, name: "ampere-square-hours" },
    { id: 247, name: "joule-per-hours" },
    { id: 248, name: "cubic-feet-per-day" },
    { id: 249, name: "cubic-meters-per-day" },
    { id: 250, name: "watt-hours-per-cubic-meter" },
    { id: 251, name: "joules-per-cubic-meter" },
    { id: 252, name: "mole-percent" },
    { id: 253, name: "pascal-seconds" },
    { id: 254, name: "million-standard-cubic-feet-per-minute" },
];

module.exports = {
    units,
    count: 255,
    maxStd: 254,
    proprietaryMin: 256,
    retrieved: '2026-07-12',
    source: 'https://raw.githubusercontent.com/bacnet-stack/bacnet-stack/master/src/bacnet/bacenum.h',
};
